### ISSUE TITLE
Extensions: Can't add extension

### ISSUE THREAD

**Issue by 1fexd** [Ulauncher/Ulauncher#1198] opened 2023-02-06 11:44 UTC
### Environment

Not relevant

### Bug description

Submitting an extension fails

![image](https://user-images.githubusercontent.com/58902674/216963147-a8db1caf-b611-49a1-85c5-c82324c8df99.png)

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment] 2023-02-06 18:28
Duplicate of https://github.com/Ulauncher/ext-api.ulauncher.io/issues/18, but thanks for making me aware. I wasn't subbed to that repo and didn't see this until now.

**Closed by friday** 2023-02-06 18:28 UTC
Labels: bug
