### ISSUE TITLE
Up down arrows skip results in xfce + fcitx

### ISSUE THREAD

**Issue by CleonH** [Ulauncher/Ulauncher#339] opened 2019-01-24 16:47 UTC
Similar Issue with #187  at manjaro-xfce

**Steps to reproduce:**
when I using FCITX, this issue appears,
$ ps aux |grep fcitx
> fcitx
> /usr/bin/dbus-daemon --syslog --fork --print-pid 4 --print-address 6 --config-file /usr/share/fcitx/dbus/daemon.conf
> /usr/bin/fcitx-dbus-watcher  unix:abstract=/tmp/dbus-XXXX

while using IBUS, this issue is gone.
> killall fcitx 
> ibus-daemon --xim

**Ulauncher version**:   4.3.1.r4
**Linux distro**:             manjaro
**Desktop environment**: xfce4

**Logs**:

 I am using chinese input methods, below is my profile setting:
> export XMODIFIERS=@im=fcitx
> export GTK_IM_MODULE=fcitx
> export QT_IM_MODULE=fcitx

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_

**Comment by CleonH** [comment] 2019-01-24 16:51
Because IBUS input is not working well for me, Could you tell any idea to fix this issue under FCITX input env?

**Comment by CleonH** [comment] 2019-01-25 16:17
hi, @gornostal. FYI, FCITX is a Chinese input tool. 
AUR-Sublime has a fixed version with source code which might be helpful. 
> https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=sublime-text-dev-imfix-fcitx
Thanks.

**Comment by friday** [comment] 2019-01-27 10:48
I'm guessing `on_input_key_press_event` is being called twice. A "debounce" with a very small timeout should "fix" this too. Might be the "wrong" solution, it but should work.

https://github.com/Ulauncher/Ulauncher/blob/f18e1a748144f9b625b1ae182039465b1990ecee/ulauncher/ui/windows/UlauncherWindow.py#L159-L169

**Comment by trongthanh** [comment] 2019-04-19 16:09
I'm using iBus & ibus-unikey to type Vietnamese and I experience this issue too. At first I thought it was compatibility issue with Ubuntu MATE, but turned out iBus.

My system:
- Ubuntu MATE 18.10
- DE: Mate Desktop 1.20 
- Ulauncher v4.3.2.r8

@CleonH In your report, you said that iBus was working for you. Can you show me what iBus settings that prevent this issue from happening?

**Comment by BlakeRain** [comment] 2019-08-04 17:19
I have been having this issue with the double-keypress when running in MATE. I found that adding a `return True` to the branches that test for the arrow keys alleviates the issue:

```python
 def on_input_key_press_event(self, widget, event): 
     keyval = event.get_keyval() 
     keyname = Gdk.keyval_name(keyval[1]) 
     alt = event.state & Gdk.ModifierType.MOD1_MASK 
     Search.get_instance().on_key_press_event(widget, event, self._get_user_query()) 
  
     if self.results_nav: 
         if keyname == 'Up': 
             self.results_nav.go_up()
             return True
         elif keyname == 'Down': 
             self.results_nav.go_down() 
             return True
```

**Comment by gornostal** [comment] 2019-09-19 11:40
Thanks for the hint @BlakeRain.
I'll try to reproduce it and confirm if that solution works. Either way I'm going to include the change in the next release.

**Comment by gornostal** [comment] 2019-09-21 15:53
@BlakeRain could you please try the latest dev release (v5.3.0~beta2) and confirm the issue is fixed for you?

I've tried to reproduce the issue on previous Ulauncher version in Ubuntu Mate, but I didn't see it.

**Comment by gornostal** [comment] 2019-09-22 12:42
The fix is included in the stable release too. 
Closing the issue. Please reopen if needed

**Closed by gornostal** 2019-09-22 12:42 UTC
Labels: Python, bug, severity-low

**Comment by BlakeRain** [comment] 2019-09-23 16:18
Fixes the problem :+1:
