### ISSUE TITLE
Feature: Add an action to type the text

### ISSUE THREAD

**Issue by ababak** [Ulauncher/Ulauncher#311] opened 2018-10-16 07:55 UTC
CopyToClipboard action is nice but in many cases, it is used just to prepare some text for the user to paste into the foreground application.
It would be great to have an action that could type some text without spoiling an existing clipboard or press a ctrl-v (ctrl-shift-v for terminals) and then restore a previous clipboard.

**Comment by friday** [comment] 2018-10-17 11:45
I agree. A paste action would be nice.

**Comment by gornostal** [comment] 2018-10-21 05:59
Thanks for the feature request.

I'll keep this issue open to see how many users would like that new action too.

**Comment by friday** [comment] 2019-01-07 10:59
I've been trying to do this for an extension, but it seems like it's not possible :( (unless you control the apps receiving the text) https://github.com/Keruspe/GPaste/issues/119#issuecomment-91868640

**Comment by friday** [comment] 2021-09-05 05:40
Closing this in favor of the new issue #804 which has more technical info.

**Closed by friday** 2021-09-05 05:40 UTC
Labels: feature, contributor-friendly, Python

**Comment by art-lucas** [comment] 2024-01-23 07:29
I'm using Ubuntu 22.04 with Ulauncher and CopyQ. I've also installed and activated the Ulauncher extension two-factor-authenticator (https://github.com/endorama/ulauncher-two-factor-authenticator), which is now working well. 
CopyQ works as intended. 
However, after launching Ulauncher, activating two-factor-authenticator (keyaord: `2fa`), and hitting `Enter` or `Alt+1` to select the first entry, there's nothing in the clipboard, i.e., CopyQ.
Any idea how to fix/debug this?
