### ISSUE TITLE
Search by Exec Name

### ISSUE THREAD

**Issue by ryanerwin** [Ulauncher/Ulauncher#344] opened 2019-02-08 08:48 UTC
**Steps to reproduce:**
Open Ulauncher and start typing:
gnome-control-center

You'll get zero hits... Even though this is the name that underlies the settings app...

Would be very helpful if the exec name was also queried against as sometimes you almost know the name of the binary, and often times the "Name" and the "Exec" are quite different.

I think that the build in KDE launcher allowed searching by exec name and was very helpful for me...

**Ulauncher version**: v4.3.1r4
**Linux distro**: Arch
**Desktop environment**: Gnome

**Comment by friday** [comment] 2019-02-08 17:34
Exec is already supported. Are you sure they're just not hidden? See #296 and https://github.com/friday/ulauncher-gnome-settings

![screenshot from 2019-02-08 18-18-07](https://user-images.githubusercontent.com/515120/52494313-f332e600-2bcd-11e9-8fef-0730f9d76274.png)
![screenshot from 2019-02-08 18-19-30](https://user-images.githubusercontent.com/515120/52494786-29bd3080-2bcf-11e9-8943-7dfc3c61ab02.png)
![screenshot from 2019-02-08 18-19-47](https://user-images.githubusercontent.com/515120/52494788-2aee5d80-2bcf-11e9-82e8-9351d6da0723.png)
![screenshot from 2019-02-08 18-26-44](https://user-images.githubusercontent.com/515120/52494789-2aee5d80-2bcf-11e9-949d-0f22bf17dea8.png)

**Comment by gornostal** [comment] 2019-02-23 18:11
Searching by exec name works for me too.
I'm closing this issue as "cannot reproduce"

Please reopen if needed

**Closed by gornostal** 2019-02-23 18:11 UTC

**Comment by ryanerwin** [comment] 2019-02-23 18:42
You are correct. Searching by exec name does work, it's just the UI for it with gnome (like your eog example) is very strange and threw me off (since the executable name is often completely different from the .desktop file "name" field.

Maybe you could somehow include the exec name in the 2nd line of details?

**Comment by gornostal** [comment] 2019-02-23 20:47
@ryanerwin not all Exec names make sense.
For example, I'm using Elementary OS and Exec name for a music player is `noise` for some reason.
Also, system settings have the same exec name (`unity-control-center`) but different arguments.

It will be difficult to put that into the second screen without ruining the UX
