### ISSUE TITLE
can't see the preferences and about window

### ISSUE THREAD

**Issue by sy2un** [Ulauncher/Ulauncher#598] opened 2020-07-31 08:38 UTC
### Steps to reproduce
1.  start ulauncher
2.  click the ulauncher icon(in my system,It's in the top right corner of the toolbar), choose preferences or about
3.  there is a window with nothing will be open

when i move the mouse cursor to the window area, the cursor changed,  and can click 

error image:
![error](https://user-images.githubusercontent.com/2315174/89017342-c12abc00-d34c-11ea-824e-761fd07cddc8.jpg)

### Environment
**Ulauncher version**:
ulauncher_5.8.0_all.deb

**Linux distro**:
Linux version 5.4.0-42-generic (buildd@lgw01-amd64-038) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)) #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020

**Desktop environment**:
ubuntu-wayland

**Comment by Soczawa** [comment] 2020-08-04 15:08
I have the same issue on one of my machines running Fedora 32. It has something to do Wayland, as it works fine on Xorg.

**Comment by laverdone** [comment] 2020-08-04 20:08
Same issue on Ubuntu 20.04 wayland session

**Comment by stevesong** [comment] 2020-08-06 14:57
Duplicate of https://github.com/Ulauncher/Ulauncher/issues/114  See suggested workarounds there.

**Comment by pgqz53** [comment] 2020-08-17 06:23
Here is a different and easier workaround for 5.8 (not sure about earlier versions) running on Gnome + Wayland:
Assuming you have enabled autostart, simply change the exec entry in `~/.config/autostart/ulauncher.desktop` to `Exec=/usr/bin/ulauncher --hide-window`. Save and restart your DE, everything will work normally now :)

**Comment by gambledor** [comment] 2020-11-06 11:35
for 5.8.1 this workaround does not work

**Comment by friday** [comment] 2021-10-04 20:49
I'm closing as a duplicate of #114.

**Closed by friday** 2021-10-04 20:49 UTC
