### ISSUE TITLE
Slow Reaction / Opening on initial first search on all ULauncher versions above 5.6.0    (5.6.1 - 5.9.0)

### ISSUE THREAD

**Issue by leirbag28** [Ulauncher/Ulauncher#692] opened 2021-02-10 18:35 UTC
### Steps to reproduce
1. Open ULauncher (That already booted automatically as a Startup Item) by pressing CTRL + SPACE to open and search....and type something
2. Usually starts and shows results instantly which 5.6.0 DOES do!
3. Press ENTER after selecting item you were searching for

### Current behavior
Works perfect

### Expected behavior
To work exactly like this as SPEEDY in opening for the first time search only for Versions above 5.6.0. ....ALL Versions work fine after that initial first time delay to respond...but that fist time makes a difference, since everyone who uses ULAuncher WILL experience because they open ULAuncher at least Once.

### Environment
**Ulauncher version**: 5.6.0
**Linux distro**: Ubuntu 18.04 MATE 64bit running on an Acer Chromebook C720p touchscreen model
**Desktop environment**: MATE 1.20.1
[5b7130f02c345c6c06572923b30a844f-50c3ea2f6ffa5749eac228eb49e2888eed14a62c.zip](https://github.com/Ulauncher/Ulauncher/files/5960594/5b7130f02c345c6c06572923b30a844f-50c3ea2f6ffa5749eac228eb49e2888eed14a62c.zip)

### Logs
 https://gist.github.com/leirbag28/5b7130f02c345c6c06572923b30a844f

**Comment by friday** [comment] 2021-08-13 14:28
Duplicate of #693

**Closed by friday** 2021-08-13 14:28 UTC
