### ISSUE TITLE
Settings menu doesn't load

### ISSUE THREAD

**Issue by BaigGam3rss** [Ulauncher/Ulauncher#825] opened 2021-10-04 20:29 UTC
### Steps to reproduce
1.install Ulauncher from .deb package
2.Start Ulauncher
3.Open settings

### Current behavior
Settings menu is just a white sreen

### Environment
Ulauncher version:
5.14.0
Linux distro:
5.10.0-kali9-amd64
Desktop environment:
xfce

### Logs
https://gist.github.com/BaigGam3rss/ebb9297066f272365fb7db005fafa2bc

**Comment by friday** [comment] 2021-10-04 20:51
I'm closing as a duplicate of #114. Unfortunately it's a hard one to fix, but you may be able to use a workaround from that issue's comments.

**Closed by friday** 2021-10-04 20:51 UTC
