### ISSUE TITLE
Error while installing via repository Ulauncher on Debian bullseye

### ISSUE THREAD

**Issue by tukanos** [Ulauncher/Ulauncher#972] opened 2022-02-10 08:44 UTC
### Description

I wanted to install your Ulauncher via the repository like suggested on your pages:
```
Install via PPA:

sudo add-apt-repository ppa:agornostal/ulauncher && sudo apt update && sudo apt install ulauncher
```

I got these warning/errors:

1) Using the apt-key is deprecated.  There should be a keyring file in the  `/etc/apt/trusted.gpg.d` instead of apt-key.

The warning:
```
add-apt-repository ppa:agornostal/ulauncher 
 Application launcher for Linux
 More info: https://launchpad.net/~agornostal/+archive/ubuntu/ulauncher
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpe9z4tdh4/pubring.gpg' created
gpg: /tmp/tmpe9z4tdh4/trustdb.gpg: trustdb created
gpg: key FAF1020699503176: public key "Launchpad PPA for Aleksandr Gornostal" imported
gpg: Total number processed: 1
gpg:               imported: 1
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
gpg: no valid OpenPGP data found.
```
**Note:** `apt-key will last be available in Debian 11 and Ubuntu 22.04.`

2) There is no release file:
`E: The repository 'http://ppa.launchpad.net/agornostal/ulauncher/ubuntu jammy Release' does not have a Release file.`  The repository is added twice. Why?  First is ignored and second gives the error.

The complete log:
```
root@magnetron:~# apt update
Ign:1 http://ppa.launchpad.net/agornostal/ulauncher/ubuntu jammy InRelease
Hit:2 https://security.debian.org/debian-security bullseye-security InRelease  
Hit:3 https://deb.debian.org/debian bullseye InRelease                         
Hit:4 https://deb.debian.org/debian bullseye-updates InRelease                 
Hit:5 https://deb.debian.org/debian bullseye-backports InRelease               
Err:6 http://ppa.launchpad.net/agornostal/ulauncher/ubuntu jammy Release       
  404  Not Found [IP: 91.189.95.85 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/agornostal/ulauncher/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Expecting:

The guide to list adding a key without apt-key now.  Like described here [apt-key Is Deprecated. How To Add OpenPGP Repository Signing Keys Without It On Debian, Ubuntu, Linux Mint, Pop!_OS, Etc.](https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html).

The repository to be added only once and also added with `https` and not `http` only.

**Comment by tukanos** [comment] 2022-02-10 10:30
I have managed to do a correct import.  I'm sure there is a better way, but this works for me.

The steps:

1) Importing the gpg key under ordinary user
`gpg --keyserver keyserver.ubuntu.com --recv 0xfaf1020699503176`

2) Create a binary gpg file from it
`gpg --export --armor 0xfaf1020699503176 | gpg --dearmor | tee Ulauncher.gpg`

3) copy it to `trusted.gpg.d`
`cp /home/<user>/Downloads/Ulauncher.gpg /etc/apt/trusted.gpg.d/`

4) Create `agornostal-ubuntu-ulauncher-focal.list` at `/etc/apt/sources.list.d` with:
```
deb [arch=amd64] https://ppa.launchpadcontent.net/agornostal/ulauncher/ubuntu focal main 
deb-src [arch=amd64] https://ppa.launchpadcontent.net/agornostal/ulauncher/ubuntu focal main 
```
5) Run the `apt update && apt install ulauncher`

**Note:**  When trying to install the `impish` version I got an error during install:

```
dpkg-deb: error: archive '/tmp/apt-dpkg-install-fm41Kk/5-ulauncher_5.14.3-0ubuntu1ppa1~impish_all.deb' uses unknown compression for member 'control.tar.zst', giving up
```
So till [dpkg-deb supports zstd](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892664) you have to use focal for ulauncher.

**Comment by friday** [comment] 2022-06-18 21:20
The first part of the issue is just Launchpad being really really dumb and assuming that any time someone on a distro that the PPA maintainer hasn't packaged for they want the latest *Ubuntu* release, rather than the latest package uploaded, or a metter of fact error saying "The PPA doesn't have a package for your distro". So it's basically broken by design. You can see the supported distros in the overview: https://launchpad.net/~agornostal/+archive/ubuntu/ulauncher/+packages.

We haven't packaged for any Debian distro, and I'm not sure w should/can use Launchpad to package for Debian. I assume we could just add release targets for Debian the same way as Ubuntu, but I haven't seen anyone else do this?

The key signing part may be due to the fact that we need to update our key signing to a newer/safer option.

I was able to shorten what you did into some easier steps:

```sh
sudo apt update
sudo apt install software-properties-common gnupg # debian's software-properties-common requires gnupg, but doesn't specify it
sudo add-apt-repository -r ppa:agornostal/ulauncher # Remove ppa:agornostal/ulauncher PPA if you added it
sudo add-apt-repository "deb http://ppa.launchpad.net/agornostal/ulauncher/ubuntu focal main"
gpg --keyserver keyserver.ubuntu.com --recv 0xfaf1020699503176
gpg --export --armor 0xfaf1020699503176 | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/Ulauncher.gpg
```

**Comment by friday** [comment] 2022-06-18 21:25
Assigning @gornostal since he's the key used for signing and only one with access to update the website with the installation instructions also.

**Comment by tukanos** [comment] 2022-06-20 10:40
> The first part of the issue is just Launchpad being really really dumb and assuming that any time someone on a distro that the PPA maintainer hasn't packaged for they want the latest _Ubuntu_ release, rather than the latest package uploaded, or a matter of fact error saying "The PPA doesn't have a package for your distro". So it's basically broken by design. You can see the supported distros in the overview: https://launchpad.net/~agornostal/+archive/ubuntu/ulauncher/+packages.
> 
> We haven't packaged for any Debian distro, and I'm not sure we should/can use Launchpad to package for Debian. I assume we could just add release targets for Debian the same way as Ubuntu, but I haven't seen anyone else do this?
> 
> The key signing part may be due to the fact that we need to update our key signing to a newer/safer option.
> 
> I was able to shorten what you did into some easier steps:
> 
> ```shell
> sudo apt update && sudo apt install gnupg
> gpg --keyserver keyserver.ubuntu.com --recv 0xfaf1020699503176
> gpg --export 0xfaf1020699503176 | sudo tee /usr/share/keyrings/ulauncher-archive-keyring.gpg
> echo "deb [signed-by=/usr/share/keyrings/ulauncher-archive-keyring.gpg] http://ppa.launchpad.net/agornostal/ulauncher/ubuntu focal main" | sudo tee -a /etc/apt/sources.list
> sudo apt update
> sudo apt install ulauncher
> ```
> 
> This is safer, because it specifically trusts the key only for the ulauncher package.

Thank you for making more consistent.  Only one comment.  I think it is better to create separate list at `/etc/apt/sources.list.d/` (I have there `agornostal-ubuntu-ulauncher-focal.list`) than put it into the distro list `/etc/apt/sources.list`.

**Comment by friday** [comment] 2022-06-21 07:49
I included that change. Also made a PR to the website repo so @gornostal can save some time when he's able to deal with this (I can add it to the repo, but not deploy the website) https://github.com/Ulauncher/ulauncher.io/pull/16

**Comment by friday** [comment] 2022-07-02 10:11
PR has been merged and the Debian instructions are on https://ulauncher.io/ now, so I'm closing this issue :)

**Comment by tukanos** [comment] 2022-07-06 12:49
@friday Thank you for your work :).

**Comment by troycurtisjr** [comment] 2022-10-31 15:00
Looks like this didn't actually get closed, so I'll do it now. We can reopen if it really hasn't been addressed after all.

**Closed by troycurtisjr** 2022-10-31 15:00 UTC
Labels: enhancement
