### ISSUE TITLE
Move dialog location

### ISSUE THREAD

**Issue by amithiel** [Ulauncher/Ulauncher#718] opened 2021-03-25 18:59 UTC
Hi! Is it possible to move the dialog location? It's not centered on my Manjaro XFCE install, and it's messing around with my OCD :dancers: 
cheers

**Comment by troycurtisjr** [comment] 2021-08-12 02:25
Can you post a snapshot?

**Comment by friday** [comment] 2021-08-12 13:04
It's horizontally positioned more to the top to give room to the result list. In addition I think it fails to center on Wayland.

Either way I think this is a good idea. It could be good to be able to move it around in case you for exanple have to do some calculations based on information on the screen, open Ulauncher and then Ulauncher covers that part.

I don't know how easy or hard it would be though, and it's not something I consider important.

**Comment by friday** [comment] 2021-08-25 05:29
Closing as a duplicate of #741. If this is not what you meant, let us know.

**Closed by friday** 2021-08-25 05:29 UTC
Labels: details-clarification
