### ISSUE TITLE
Open port 5054 by ulauncher

### ISSUE THREAD

**Issue by elleven11** [Ulauncher/Ulauncher#668] opened 2020-12-17 14:51 UTC
## Question
Hello, I am on Arch Linux and have installed Ulauncher through the AUR.
By running netstat -lntup i can see that ulauncher has opened the port 5054 on LISTEN state
Furthermore, if i run lsof -i i can see this:
`
ulauncher  5816 elleven   10u  IPv4  34136      0t0  TCP localhost:rlm-admin (LISTEN)

ulauncher  5816 elleven   18u  IPv4  30106      0t0  TCP localhost:rlm-admin->localhost:54038 (ESTABLISHED)

ulauncher  5816 elleven   19u  IPv4  30107      0t0  TCP localhost:rlm-admin->localhost:54040 (ESTABLISHED)

python     5916 elleven    7u  IPv4  33447      0t0  TCP localhost:54040->localhost:rlm-admin (ESTABLISHED)

python     5923 elleven    8u  IPv4  34161      0t0  TCP localhost:54038->localhost:rlm-admin (ESTABLISHED)
`
The python process seems to be related to the Ulauncher one.

Is this all normal or should i be concerned? It looks like a backdoor to me.

Thank you

**Comment by simonwoerpel** [comment] 2020-12-18 14:23
see https://github.com/Ulauncher/Ulauncher/issues/456

**Comment by gornostal** [comment] 2021-01-20 20:18
> Is this all normal or should i be concerned? It looks like a backdoor to me.

It's expected. Definitely not ideal. I understand your concern.

Closing as a duplicate of #456

**Closed by gornostal** 2021-01-20 20:18 UTC
