### ISSUE TITLE
Support additional desktop actions inside desktop files

### ISSUE THREAD

**Issue by ultra-azu** [Ulauncher/Ulauncher#1220] opened 2023-04-08 16:23 UTC
### Description

See here: https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#extra-actions

Currently I need it for steam. That way I can, for example, enter Big Picture mode if I need to by just looking it up. Here is the example steam flatpak desktop file (I renamed it to .txt so that Github accepts it): 
[com.valvesoftware.Steam.desktop.txt](https://github.com/Ulauncher/Ulauncher/files/11183668/com.valvesoftware.Steam.desktop.txt)

 

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

### Ulauncher v6

- [X] I have checked and couldn't find my suggestion in v6.

**Comment by friday** [comment] 2023-04-08 19:29
Duplicate of #476
We want to support this eventually, but it's not on the immediate roadmap.

**Closed by friday** 2023-04-08 19:29 UTC
Labels: enhancement
