### ISSUE TITLE
Can't add or change Shortcuts

### ISSUE THREAD

**Issue by Cediddi** [Ulauncher/Ulauncher#101] opened 2017-03-08 09:25 UTC
Ubuntu 14.04, Ulauncher 2.0.30.r3_all

When I first click a button in Shortcuts menu, it'll work, but after that, any key I click will grayout the whole window. I checked the logs, nothing important there.

---

Installing this package will potentially fix the issue: [gir1.2-webkit2-4.0](https://github.com/Ulauncher/Ulauncher/releases/download/2.1.1.r1/gir1.2-webkit2-4.0_2.14.5-0ubuntu0.16.10.1_amd64.deb)

```
$ sudo dpkg -i <filename.deb>
$ sudo apt-get install -f
```

**Comment by gornostal** [comment] 2017-03-08 10:31
Interesting...
Looks like it just hangs up.
I cannot reproduce the problem on a clean Ubuntu 14.04 installation though.

Is there anything special about your Ubuntu 14.04?
What kind of CPU and how much RAM do you have?

**Comment by gornostal** [comment] 2017-03-31 19:09
If the issue still persists, could you run ulauncher from terminal like this `ulauncher -v` and copy output here?
I'll also need more info about resources on your PC. I've seen something similar on my VBox with limited RAM and CPU, so that can explain the issue.

Please reopen when you gather more info.

**Comment by Cediddi** [comment] 2017-04-01 08:25
Sorry for late reply. I removed the application. It's still here in 2.0.30.r3 My special case is I actually have Linux Mint 17.3 Cinnamon which is based on ubuntu 14.04 + cinnamon interface (gnome3 fork). Almost all packages are installed from official ubuntu repo, so binaries are 100% compatible. Maybe it's the Cinnamon.

When the UI breaks, no new log is produced but when I ctrl-c it, raises a segmentation fault. 

Here's the before log:

    2017-04-01 11:20:10,237:DEBUG:ulauncher: set_up_logging() 'logging enabled'
    2017-04-01 11:20:10,237:INFO:ulauncher: main() 'Ulauncher version 2.0.30.r3'
    2017-04-01 11:20:10,237:INFO:ulauncher: main() 'GTK+ 3.10.8'
    2017-04-01 11:20:10,238:DEBUG:ulauncher: main() 'Starting a new instance...'
    2017-04-01 11:20:10,248:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'ulauncher_window','destroy', 'on_destroy''
    2017-04-01 11:20:10,248:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event''
    2017-04-01 11:20:10,248:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event''
    2017-04-01 11:20:10,249:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'input','key_press_event', 'on_input_key_press_event''
    2017-04-01 11:20:10,250:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_mnu_about_activate''
    2017-04-01 11:20:10,250:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_mnu_close_activate''
    2017-04-01 11:20:10,250:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_preferences_dialog_destroyed''
    2017-04-01 11:20:10,250:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_mnu_preferences_activate''
    2017-04-01 11:20:10,250:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_input_changed''
    2017-04-01 11:20:10,252:DEBUG:ulauncher.utils.display: get_screens() 'Found 1 monitor(s).'
    2017-04-01 11:20:10,252:DEBUG:ulauncher.utils.display: get_screens() '  Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080'
    2017-04-01 11:20:10,267:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/libreoffice5.3-calc.desktop": constructor returned NULL'
    2017-04-01 11:20:10,271:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/libreoffice5.3-base.desktop": constructor returned NULL'
    2017-04-01 11:20:10,278:INFO:ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() 'Trying to bind app hotkey: <Primary>space'
    2017-04-01 11:20:10,281:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/brasero-nautilus.desktop": constructor returned NULL'
    2017-04-01 11:20:10,285:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/libreoffice5.3-writer.desktop": constructor returned NULL'
    2017-04-01 11:20:10,288:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/mintinstall-kde.desktop": constructor returned NULL'
    2017-04-01 11:20:10,288:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/jetbrains-pycharm.desktop": constructor returned NULL'
    2017-04-01 11:20:10,296:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/libreoffice5.3-impress.desktop": constructor returned NULL'
    2017-04-01 11:20:10,304:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/libreoffice5.3-draw.desktop": constructor returned NULL'
    2017-04-01 11:20:10,305:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/libreoffice5.3-xsltfilter.desktop": constructor returned NULL'
    2017-04-01 11:20:10,305:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/libreoffice5.3-math.desktop": constructor returned NULL'
    2017-04-01 11:20:10,309:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/usr/share/applications/libreoffice5.3-startcenter.desktop": constructor returned NULL'
    2017-04-01 11:20:10,354:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/home/cediddi/.local/share/applications/userapp-Thunderbird-ILSDKY.desktop": constructor returned NULL'
    2017-04-01 11:20:10,355:WARNING:ulauncher.utils.desktop: read_desktop_file() 'Unable to read desktop file "/home/cediddi/.local/share/applications/userapp-acroread-UVOSJY.desktop": constructor returned NULL'
    2017-04-01 11:20:10,554:WARNING:ulauncher.utils.icon_loader: get_app_icon_pixbuf() 'Could not load icon for im-chooser. E: Icon 'im-chooser' not present in theme'
    2017-04-01 11:20:10,647:INFO:ulauncher.search.apps.app_watcher: start() 'Finished scanning directories for desktop files. Indexed 358 applications'
    2017-04-01 11:20:10,654:DEBUG:ulauncher.search.apps.app_watcher: start() 'Start watching desktop files...'
    2017-04-01 11:20:14,830:DEBUG:ulauncher.utils.display: get_screens() 'Found 1 monitor(s).'
    2017-04-01 11:20:14,830:DEBUG:ulauncher.utils.display: get_screens() '  Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080'
    2017-04-01 11:20:16,903:DEBUG:ulauncher.ui.windows.UlauncherWindow: activate_preferences() 'create new preferences_dialog'
    2017-04-01 11:20:16,922:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_scheme_callback''
    2017-04-01 11:20:16,922:DEBUG:ulauncher.ui.windows.Builder: log_unconnected_functions() 'Not connected to builder 'on_hotkey_set''
    2017-04-01 11:20:16,944:DEBUG:ulauncher.ui.windows.Builder: __init__() 'consider using a pythonic name instead of design name 'new-hotkey-label''
    2017-04-01 11:20:16,944:DEBUG:ulauncher.ui.windows.Builder: __init__() 'consider using a pythonic name instead of design name 'hotkey-dialog-vbox1''
    2017-04-01 11:20:16,948:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event''
    2017-04-01 11:20:16,949:DEBUG:ulauncher.ui.windows.Builder: do_connect() 'connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event''
    2017-04-01 11:20:17,156:INFO:ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() 'API call /get/all'

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
    2017-04-01 11:20:21,859:INFO:ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_shortcut_get_all() 'Handling /shortcut/get-all'

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_ref: assertion 'object->ref_count > 0' failed

    (WebKitWebProcess:24542): GLib-GObject-CRITICAL **: g_object_unref: assertion 'object->ref_count > 0' failed
    2017-04-01 11:20:31,399:INFO:ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_shortcut_delete() 'Delete shortcut: {"callback": "__jp2", "id": "bd1e5725-ca2f-4bc7-b90b-8a42bf08e771"}'

And here's the after ctrl-c log:

    2017-04-01 11:20:49,067:DEBUG:ulauncher.ui.windows.UlauncherWindow: on_preferences_dialog_destroyed() 'on_preferences_dialog_destroyed'

    ^C2017-04-01 11:21:18,771:INFO:ulauncher: main() 'On KeyboardInterrupt'
    [1]    24516 segmentation fault  ulauncher -v

**Comment by gornostal** [comment] 2017-04-01 08:52
This may by caused by a bug in gir1.2-webkit2-3.0. Try updating that package.
Ideally, you would want to install gir1.2-webkit2-4.0, but I doubt it's available for Ubuntu 14.04

**Comment by Cediddi** [comment] 2017-04-01 08:53
So, no support for 14.04 then.

**Comment by gornostal** [comment] 2017-04-01 09:33
Can you copy output from `apt-cache show gir1.2-webkit2-3.0`?
I'll compare with what I have on my Ubuntu 14.04

**Comment by Cediddi** [comment] 2017-04-01 10:34
Here,

    Package: gir1.2-webkit2-3.0
    Priority: optional
    Section: introspection
    Installed-Size: 170
    Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Original-Maintainer: Debian WebKit Maintainers <pkg-webkit-maintainers@lists.alioth.debian.org>
    Architecture: amd64
    Source: webkitgtk
    Version: 2.4.10-0ubuntu0.14.04.1
    Depends: gir1.2-javascriptcoregtk-3.0 (= 2.4.10-0ubuntu0.14.04.1), gir1.2-glib-2.0, gir1.2-gtk-3.0 (>= 3.10.0), gir1.2-soup-2.4, libwebkit2gtk-3.0-25 (>= 2.3.90)
    Conflicts: gir1.0-webkit-3.0, gobject-introspection-repository
    Filename: pool/main/w/webkitgtk/gir1.2-webkit2-3.0_2.4.10-0ubuntu0.14.04.1_amd64.deb
    Size: 26608
    MD5sum: 10f01fdb6b86c47d78925ec140a560a7
    SHA1: 0b42a84f52ed2c7a312edc2467fbc843e1e1bf6d
    SHA256: a4f4d9376e2e67a91ecb2dea6676c959f1bfaa2c77b9ab8849e99687aa812cd5
    Description-en: WebKit2 API layer for WebKitGTK+ - GObject introspection data
     WebKit is a web content engine, derived from KHTML and KJS from KDE, and
     used primarily in Apple's Safari browser.  It is made to be embedded in
     other applications, such as mail readers, or web browsers.
     .
     It is able to display content such as HTML, SVG, XML, and others. It also
     supports DOM, XMLHttpRequest, XSLT, CSS, JavaScript/ECMAScript and more.
     .
     WebKit2 is an API layer for WebKit designed from the ground up to
     support a split process model, where the web content lives in a
     separate process from the application UI.
     .
     This build comes from the GTK+ port of WebKit (API version 3.0).
     .
     This package contains introspection data, which can be used by
     packages using the GIRepository format to generate dynamic bindings.
    Description-md5: 930ecccf58bd28080ded64da6b9507d4
    Homepage: http://webkitgtk.org/
    Bugs: https://bugs.launchpad.net/ubuntu/+filebug
    Origin: Ubuntu
    Supported: 9m

    Package: gir1.2-webkit2-3.0
    Priority: optional
    Section: introspection
    Installed-Size: 167
    Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
    Original-Maintainer: Debian WebKit Maintainers <pkg-webkit-maintainers@lists.alioth.debian.org>
    Architecture: amd64
    Source: webkitgtk
    Version: 2.4.0-1ubuntu2
    Depends: gir1.2-javascriptcoregtk-3.0 (= 2.4.0-1ubuntu2), gir1.2-glib-2.0, gir1.2-gtk-3.0 (>= 3.10.0), gir1.2-soup-2.4, libwebkit2gtk-3.0-25 (>= 2.3.90)
    Conflicts: gir1.0-webkit-3.0, gobject-introspection-repository
    Filename: pool/main/w/webkitgtk/gir1.2-webkit2-3.0_2.4.0-1ubuntu2_amd64.deb
    Size: 26542
    MD5sum: 299f8981dcd927427800094e1747baae
    SHA1: b6adf050e066714f8d87220482baf2b480099cb2
    SHA256: 32803cf4521d93f46282e6408f700d510741e71ebe1f4985fd01b18a2cc8c3d7
    Description-en: WebKit2 API layer for WebKitGTK+ - GObject introspection data
     WebKit is a web content engine, derived from KHTML and KJS from KDE, and
     used primarily in Apple's Safari browser.  It is made to be embedded in
     other applications, such as mail readers, or web browsers.
     .
     It is able to display content such as HTML, SVG, XML, and others. It also
     supports DOM, XMLHttpRequest, XSLT, CSS, JavaScript/ECMAScript and more.
     .
     WebKit2 is an API layer for WebKit designed from the ground up to
     support a split process model, where the web content lives in a
     separate process from the application UI.
     .
     This build comes from the GTK+ port of WebKit (API version 3.0).
     .
     This package contains introspection data, which can be used by
     packages using the GIRepository format to generate dynamic bindings.
    Description-md5: 930ecccf58bd28080ded64da6b9507d4
    Homepage: http://webkitgtk.org/
    Bugs: https://bugs.launchpad.net/ubuntu/+filebug
    Origin: Ubuntu
    Supported: 9m

**Comment by gornostal** [comment] 2017-04-01 11:08
It's the same on my Ubuntu.
I'll look into this issue more because I was able to reproduce the bug just now.
Although errors I see are different from yours.

**Comment by Cediddi** [comment] 2017-04-01 13:30
Maybe it's the cinnamon. How can I help you? I fetched the code and ran dev-run.sh but got those errors when I try to open settings.

    file:///home/cediddi/PycharmProjects/Ulauncher/data/preferences/build/js/app.min.js:1797:36JS ERROR: TypeError: undefined is not a function (evaluating 'd.module("ngRoute",[]).info({angularVersion:"1.6.4"})')
    file:///home/cediddi/PycharmProjects/Ulauncher/data/preferences/build/js/app.min.js:39:48JS ERROR: Error: [$injector:modulerr] http://errors.angularjs.org/1.4.14/$injector/modulerr?p0=ulauncher&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.14%2F%24injector%2Fnomod%3Fp0%3Dulauncher%0Afile%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A6%3A422%0Afile%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A24%3A187%0Ab%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A23%3A252%0Afile%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A23%3A707%0Afile%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A38%3A239%0Ap%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A7%3A359%0Ag%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A38%3A86%0Adb%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A41%3A369%0Ac%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A19%3A465%0Ayc%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A20%3A275%0Ade%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A19%3A84%0Afile%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A299%3A476%0Ab%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A178%3A160%0APf%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A35%3A481%0Ad%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A35%3A425
    file:///home/cediddi/PycharmProjects/Ulauncher/data/preferences/build/js/app.min.js:1797:36JS ERROR: TypeError: undefined is not a function (evaluating 'd.module("ngRoute",[]).info({angularVersion:"1.6.4"})')
    file:///home/cediddi/PycharmProjects/Ulauncher/data/preferences/build/js/app.min.js:39:48JS ERROR: Error: [$injector:modulerr] http://errors.angularjs.org/1.4.14/$injector/modulerr?p0=ulauncher&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.14%2F%24injector%2Fnomod%3Fp0%3Dulauncher%0Afile%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A6%3A422%0Afile%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A24%3A187%0Ab%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A23%3A252%0Afile%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A23%3A707%0Afile%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A38%3A239%0Ap%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A7%3A359%0Ag%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A38%3A86%0Adb%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A41%3A369%0Ac%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A19%3A465%0Ayc%40file%3A%2F%2F%2Fhome%2Fcediddi%2FPycharmProjects%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fj2017-04-01 16:21:02,818:DEBUG:ulauncher.ui.windows.UlauncherWindow: on_preferences_dialog_destroyed() 'on_preferences_dialog_destroyed'

If I can run the project with Pycharm's debugger maybe I can catch the error. But no success so far.

**Comment by gornostal** [comment] 2017-04-01 13:51
It's not an issue with the source code, so you can save your time and quit debugging that error)
It's definitely some of the GTK libs failing. Maybe I'll find a workaround. I'm working on it now. Will keep you posted

**Comment by gornostal** [comment] 2017-04-01 14:34
As a workaround, you can install gir1.2-webkit2-4.0, which is not listed in Ubuntu 14.04 repositories.
I uploaded it to releases https://github.com/Ulauncher/Ulauncher/releases/download/2.1.1.r1/gir1.2-webkit2-4.0_2.14.5-0ubuntu0.16.10.1_amd64.deb
It can be installed with
```
$ sudo dpkg -i <filename.deb>
$ sudo apt-get install -f
```
First command will show an error, but that's OK.

After installing that package Add and Edit buttons work on my 14.04.

**Comment by Cediddi** [comment] 2017-04-01 14:40
Nope, didn't fixed the issue. Still having freezing and segmentation fault.

**Comment by gornostal** [comment] 2017-04-01 14:45
That's too bad because I don't see anything else that could fix it

**Comment by gornostal** [comment] 2017-09-03 05:52
Fixed in v3.1.1
https://ulauncher.io/#Download

**Closed by gornostal** 2017-09-03 05:52 UTC
Labels: bug, ready

**Comment by gornostal** [comment] 2017-09-03 05:53
Fixed by re-implementing Preferences in Vue.js
Angular app would crash in Ubuntu 14.04.

**Comment by Cediddi** [comment] 2017-10-30 16:41
I just saw this. Great work on switching to a lighter framework.
