### ISSUE TITLE
Switcher to enable and disable some extension

### ISSUE THREAD

**Issue by mearrypav** [Ulauncher/Ulauncher#962] opened 2022-01-22 10:55 UTC
### Description

Thanks for the app, but isn't it time to add a switch so you can turn some extension on and off? 

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the [existing enhancement requests](https://github.com/Ulauncher/Ulauncher/labels/enhancement) before suggesting this.

**Comment by friday** [comment] 2022-01-22 12:56
Duplicate of #677

**Closed by friday** 2022-01-22 12:56 UTC
Labels: enhancement

**Comment by friday** [comment] 2022-01-22 13:03
Also, we _want_ lots of things, but someone has to put the time in and implement them for them to happen. No one is paid for this and we've already done an insane amount of of work to improve the app lately, me in particular. If you want to help out it's highly appreciated, but otherwise please don't imply something *should* be done :)
