### ISSUE TITLE
Ulauncher preferences are a blank window within a VM; workaround?

### ISSUE THREAD

**Issue by CottonEaster** [Ulauncher/Ulauncher#170] opened 2017-10-09 16:11 UTC
**Steps to reproduce:**
Install Mint 18.2 in a virtual machine, via VirtualBox, in Windows 8.1.
Install ulauncher.
Try to access ulauncher's preferences.

**Ulauncher version**: 3.1.2rc
**Linux distro**: Mint 18.2
**Desktop environment**: Cinnamon

**Logs**:
[Here](https://gist.github.com/CottonEaster/31aa0ffd13041ac4b9d6381330342a80).

I tried the [fix on this page](https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached) but it did not seem to work.

If a fix isn't forthcoming, I'd like a least to be able to edit the preferences manually. How do I do that, please?

**Comment by gornostal** [comment] 2017-10-15 07:30
Hi,
Sorry for the delay.
All the preferences are in `~/.config/ulauncher`, but let's try to fix the issue first.

Looks like you've got two issues with Ulauncher,
One with pyinotify, which can be fixed using [this](https://github.com/Ulauncher/Ulauncher/issues/51) guide.
And another with preferences window being blank. 

I've tried to run Ulauncher v3.1.2 on Mint 17.2 and preferences opened fine.
Could you rename `~/.config/ulauncher` and then restart the app? It will create default configs. Perhaps they have been corrupted or something.
Please also try updating the app to v3.2.

**Comment by CottonEaster** [comment] 2017-10-15 22:26
Thanks.

I applied the pyinotify fix, and then renamed the config file, then installed the new version of Ulauncher, then rebooted. Result: preferences window is still blank. By the way: the preference window works fine on my _real_ editions - not virtual - of Mint.

**Comment by gornostal** [comment] 2017-10-16 10:05
I tried to reproduce exactly as you described, except VBox is running on Linux in my case.
v3.1.2 and v3.2.1 works fine.

I'm not sure what I can do here. According to the logs you get "Segmentation fault" error, which doesn't tell much about a cause. 

You could try different guest OS unless you must use Mint.

**Comment by CottonEaster** [comment] 2017-10-16 13:49
I think I'll edit the preferences manually. Thanks for the efforts that you did make to get to the bottom of the problem. (Also: I wonder whether themes might be playing a role . .)

**Comment by gornostal** [comment] 2017-10-16 14:42
No problem.
I'll leave this bug open for some time. Maybe someone else is having the same issue too

**Comment by gornostal** [comment] 2018-01-15 06:10
I'm closing this issue because it doesn't seem like a Ulauncher bug. I've tested it on multiple different distros and DEs in VBox.

BTW, you might try installing dev release from ulauncher.io. There was a fix for Wayland protocol. Maybe that helps.

**Closed by gornostal** 2018-01-15 06:10 UTC
Labels: bug
