### ISSUE TITLE
Fix for Ulauncher dialog not getting keyboard focus

### ISSUE THREAD

**Issue by RedBearAK** [Ulauncher/Ulauncher#1128] opened 2022-09-22 12:42 UTC
### Environment

Fedora 36, Ubuntu 22.04 (both GNOME 42+)

### Bug description

I don't know the exact cause, but I've been having a lot of trouble for quite a while with the Ulauncher dialog not receiving the keyboard focus when I use the keyboard shortcut. This has been happening on both Ubuntu 22.04 and Fedora 36. More on Fedora, I think, on multiple machines. Might have something to do with the keyboard remapper I use (Kinto.sh). So maybe this isn't happening to anyone else. But for me it's pretty bad. 

**_[ EDIT: This is definitely caused somehow by how the keymapper interacts with Ulauncher. It happens with both xkeysnail and keyszer (a fork of xkeysnail). And I can apparently bypass the issue by setting up a custom shortcut in GNOME that just launches `ulauncher-toggle` directly, rather than letting Ulauncher catch the shortcut. The shortcut is still going through the keymapper, getting transformed from one shortcut combo to another, yet there is no problem with loss of keyboard focus when it's the GNOME shell doing the work of running the toggle. So it has something to do with how Ulauncher binds to the keyboard shortcut. ]_**

**_[ EDIT 2: Seems to be particularly focused around the keymapper sending Alt+F1 to Ulauncher, remapped from Ctrl+Space. ]_**

`wmctrl` has been present on these systems, so that's not the problem. Messing with increasing the sleep delay or adding a `wmctrl` loop to `ulauncher-toggle` to try and compensate for this problem went nowhere, no matter what I tried. 

So I wrote my own solution. It works, but it's kind of a sledgehammer. It runs a script on login that constantly checks the `wmctrl` list of windows and runs the same command from `ulauncher-toggle` to bring the keyboard focus to the Ulauncher dialog whenever it appears in the list. 

Why this works very reliably when run from this separate script and yet never seems to work when I try to do something similar inside `ulauncher-toggle` is beyond me. 

The script is pretty simple but it seems to use up a lot of PIDs as it runs the `wmctrl` check in a loop. I'm sure there's a better way to make it work, maybe with Python and Xlib. If anyone wants to use it or contribute improvements it's here: 

https://github.com/RedBearAK/Fix_Ulauncher_Focus

There's a full installer/uninstaller script. 

A simpler solution to this problem is desirable. I just haven't found one. 

I think the mechanism for showing the dialog is pretty different in v6, so this is only relevant for as long as v5 is around. 

### Log output

```shell
2022-09-22 04:23:17,601 | INFO | ulauncher: main() | Ulauncher version 5.14.7
2022-09-22 04:23:17,601 | INFO | ulauncher: main() | Extension API version 2.0.0
2022-09-22 04:23:17,602 | INFO | ulauncher: main() | GTK+ 3.24.34
2022-09-22 04:23:17,602 | INFO | ulauncher: main() | Is Wayland: False
2022-09-22 04:23:17,602 | INFO | ulauncher: main() | Wayland compatibility: off
2022-09-22 04:23:17,608 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2022-09-22 04:23:17,610 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2022-09-22 04:23:17,610 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2022-09-22 04:23:17,610 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2022-09-22 04:23:17,611 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2022-09-22 04:23:17,612 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2022-09-22 04:23:17,612 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2022-09-22 04:23:17,612 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2022-09-22 04:23:17,612 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2022-09-22 04:23:17,612 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2022-09-22 04:23:17,613 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-09-22 04:23:17,613 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2022-09-22 04:23:17,621 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-09-22 04:23:17,623 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2022-09-22 04:23:17,623 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2022-09-22 04:23:17,635 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.episode6.ulauncher-system-management-direct" started. PID 246187
2022-09-22 04:23:17,638 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.tchar.ulauncher-albert-calculate-anything" started. PID 246189
2022-09-22 04:23:17,640 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.dalanicolai.gnome-tracker-extension" started. PID 246191
2022-09-22 04:23:17,644 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.fisadev.ulauncher-better-file-browser" started. PID 246193
2022-09-22 04:23:17,647 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.friday.ulauncher-gnome-settings" started. PID 246195
2022-09-22 04:23:17,649 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.zensoup.ulauncher-unicode" started. PID 246197
2022-09-22 04:23:17,659 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.ulauncher.ulauncher-emoji" started. PID 246199
2022-09-22 04:23:17,675 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 56 apps in cache
/home/kris/.local/share/ulauncher/extensions/com.github.episode6.ulauncher-system-management-direct/main.py:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
/home/kris/.local/share/ulauncher/extensions/com.github.dalanicolai.gnome-tracker-extension/main.py:3: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
2022-09-22 04:23:17,711 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/evolution-calendar.desktop": constructor returned NULL
2022-09-22 04:23:17,737 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.rkarami.ulauncher-password-generator" started. PID 246202
2022-09-22 04:23:17,737 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.noam09.ulauncher-remmina" started. PID 246206
2022-09-22 04:23:17,764 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.episode6.ulauncher-system-management-direct" connected
2022-09-22 04:23:17,770 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.episode6.ulauncher-system-management-direct"
2022-09-22 04:23:17,771 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 57 apps in the system
2022-09-22 04:23:17,771 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.15 seconds
com.github.episode6.ulauncher-system-management-direct | 2022-09-22 04:23:17,772 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-22 04:23:17,777 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.friday.ulauncher-gnome-settings" connected
2022-09-22 04:23:17,778 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.friday.ulauncher-gnome-settings"
com.github.friday.ulauncher-gnome-settings | 2022-09-22 04:23:17,780 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-22 04:23:17,781 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
/home/kris/.local/share/ulauncher/extensions/com.github.noam09.ulauncher-remmina/main.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.spawn
2022-09-22 04:23:17,851 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Alt>F1
2022-09-22 04:23:18,062 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.fisadev.ulauncher-better-file-browser" connected
2022-09-22 04:23:18,062 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.fisadev.ulauncher-better-file-browser"
com.github.fisadev.ulauncher-better-file-browser | 2022-09-22 04:23:18,063 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-22 04:23:18,083 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.dalanicolai.gnome-tracker-extension" connected
2022-09-22 04:23:18,083 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.dalanicolai.gnome-tracker-extension"
com.github.dalanicolai.gnome-tracker-extension | 2022-09-22 04:23:18,085 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-22 04:23:18,087 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.ulauncher.ulauncher-emoji" connected
2022-09-22 04:23:18,087 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.ulauncher.ulauncher-emoji"
com.github.ulauncher.ulauncher-emoji | 2022-09-22 04:23:18,088 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-22 04:23:18,119 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.rkarami.ulauncher-password-generator" connected
2022-09-22 04:23:18,120 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.rkarami.ulauncher-password-generator"
com.github.rkarami.ulauncher-password-generator | 2022-09-22 04:23:18,121 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-22 04:23:18,134 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.tchar.ulauncher-albert-calculate-anything" connected
2022-09-22 04:23:18,135 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.tchar.ulauncher-albert-calculate-anything"
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,136 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,136 | INFO | calculate_anything.utils.misc: safe_operation() | Set language
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,136 | INFO | calculate_anything.utils.misc: safe_operation() | Set default cities
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,137 | INFO | calculate_anything.utils.misc: safe_operation() | Set units conversion mode
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,137 | INFO | calculate_anything.utils.misc: safe_operation() | Set currency providers
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,137 | INFO | calculate_anything.utils.misc: safe_operation() | Set cache interval
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,137 | INFO | calculate_anything.utils.misc: safe_operation() | Set default currencies
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,137 | INFO | calculate_anything.utils.misc: safe_operation() | LanguagePreferences: lang = en_US
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,138 | INFO | calculate_anything.utils.misc: safe_operation() | TimePreferences: default_cities = [('new york city', 'US'), ('london', 'GB'), ('madrid', 'ES'), ('vancouver', 'CA'), ('athens', 'GR')]
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,138 | INFO | calculate_anything.utils.loaders.sqlite: _load() | Loaded timezone database: /home/kris/.cache/com.github.tchar.calculate-anything/timezones.sqlite3
ERROR:__main__:Remmina executable path could not be determined
2022-09-22 04:23:18,162 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.zensoup.ulauncher-unicode" connected
2022-09-22 04:23:18,162 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.zensoup.ulauncher-unicode"
com.github.zensoup.ulauncher-unicode | 2022-09-22 04:23:18,163 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-09-22 04:23:18,173 | ERROR | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.noam09.ulauncher-remmina" was terminated with code 0
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,225 | INFO | calculate_anything.utils.misc: safe_operation() | UnitsPreferences: units_conversion_mode = ConversionMode.NORMAL
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,226 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: add_provider = <calculate_anything.currency.providers.fixerio.FixerIOCurrencyProvider object at 0x7f237861eb90>
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,226 | INFO | calculate_anything.currency.service: remove_provider() | Removing provider FixerIOCurrencyProvider
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,226 | INFO | calculate_anything.currency.service: add_provider() | Adding provider FixerIOCurrencyProvider
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,226 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: cache_update_frequency = 86400
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,226 | INFO | calculate_anything.currency.service: enable_cache() | Enabling cache with update frequency = 86400
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,226 | INFO | calculate_anything.currency.cache: enable() | Enabling cache every 86400s
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,226 | INFO | calculate_anything.utils.misc: safe_operation() | CurrencyPreferences: default_currencies = ['USD', 'EUR', 'GBP', 'CAD']
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,226 | INFO | calculate_anything.currency.service: set_default_currencies() | Updating default currencies = ['USD', 'EUR', 'GBP', 'CAD']
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,226 | INFO | calculate_anything.currency.service: start() | Currency Service is running
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,227 | INFO | calculate_anything.currency.service.UpdateThread(id=d9c8b74047bb): run() | Starting thread
com.github.tchar.ulauncher-albert-calculate-anything | 2022-09-22 04:23:18,228 | INFO | calculate_anything.currency.service.UpdateThread(id=d9c8b74047bb): run() | Sleeping for 76537s
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment] 2022-09-23 11:19
I think both v5 and v6 work 100% with the keybinder library. And I believe v6 works 100% with external keybinders if you bind to `ulauncher` instead of `ulauncher-toggle`. This is a little bit slower, so we still have `ulauncher-toggle`, but I believe #1003 reintroduced the issue there. I don't use Wayland myself though. Only for testing.

I'm able to reproduce the issue in v6 with `ulauncher-toggle` if I have for example Gnome Settings in focus on one screen and launch Ulauncher when my mouse pointer is on the other screen. I think this is due to focus stealing prevention.

About your fix, I just think we could maybe try to check the focus after setting it with wmctrl and retry every time it fails. It's pretty hard to test however.

**Comment by RedBearAK** [comment] 2022-09-23 13:01
@friday 

> About your fix, I just think we could maybe try to check the focus after setting it with wmctrl and retry every time it fails. It's pretty hard to test however.

Problem is that I tried things as extreme as running the `wmctrl` command to grab focus in a loop that sent the command every 0.1 seconds or so, and ran dozens of times. No matter how many times I tried to run it, it never worked from within `ulauncher-toggle` to fix the focus issue. It only worked from the separate script. And it would work instantly. As far as I know it never failed from the separate script. 

But the good news in my case is that this seems very much focused around the Alt+F1 shortcut that Kinto.sh is remapping the Cmd+Space shortcut onto. If I use a different shortcut with the keymapper config (e.g., Shift+Ctrl+F3 or something), or disable the remap and let Ulauncher use Cmd+Space directly, or just let GNOME take over with a custom shortcut for Alt+F1, the focus problem disappears in all cases. 

I don't know too much about how it works, but the keymapper uses Xlib to monitor the active window context, and transforms some shortcuts and sends different ones to output at a fairly low level with evdev. Any other shortcut that isn't in the config file just gets left alone. Why Alt+F1 coming from evdev via the keymapper causes such a headache with Ulauncher is beyond me. Maybe it has more to do with how the keymapper uses Xlib. 

If v6 uses the same keybinding technique the same thing will probably happen. Fortunately the workarounds of just changing the shortcut in various ways all work fine. My "fix" worked but it turns out was largely a waste of time and effort.

**Comment by Sandro0000** [comment] 2022-10-29 08:44
I have also had this issue with Linux Mint 20.3 Cinnamon.
Note that I'm using Input Remapper to swap the Control and Command(Super) keys on my Mac-style keyboard, with Ulauncher set to Control+Space. Like the op, I tried resorting to bash scripts that loops wmctrl at various time delayed intervals to try and force grab focus, but this did fail.

I ended up patching Ulaunchers source code, so that it quits when it loses focus; then using cinnamon's keyboard's shortcuts, to relaunch it each time. I'm not really happy with this really hacky solution, as it now take a few seconds to open, but so far, it the only way I've been able to fix this. https://github.com/Ulauncher/Ulauncher/commit/606015dcd73f8d5b0184e21fd5e0cd995e966183

**Comment by RedBearAK** [comment] 2022-10-29 13:59
If I’m looking at the right project, Input Mapper appears to also use the Python module `evdev`, just like my key mapper `keyzser`. That seems likely to be the root of the issue. It turned out they were also some other windows besides Ulauncher that would have a focus problem when triggered with a remapped shortcut. Like the properties dialog in Nautilus, if I bring it up with Cmd+I remapped to Alt+Enter. 

@Sandro0000 

> I ended up patching Ulauncher, so that it quits when it loses focus. Then using cinnamon's keyboard's shortcuts, to relaunch it each time.

Does it not work to just use a custom Cinnamon shortcut to run `ulauncher-toggle`? Seems excessive and slow to get the whole app to quit and restart whenever it loses focus. 

As long as you avoid using a remapped shortcut combo there should be no focus issue. At least that’s how it worked for me with a custom GNOME shortcut. My modifier keys are also swapped at all times but that doesn’t trigger the focus issue.

**Comment by friday** [comment] 2022-10-29 23:25
@Sandro0000 Supporting this (not keeping Ulauncher running in the background) is pretty reasonable and something I was experimenting with/pushing for a while back for other reasons. It will launch slower this way though, and it should be optional.

I was hoping that just closing the window would be enough.

**Comment by Sandro0000** [comment] 2022-10-30 21:38
So, just to be clear, I really haven't messed around with this since April, so any updates since then haven't be tested. In particular, this https://github.com/Ulauncher/Ulauncher/commit/4c78785d10280ea6f07b2795b3e88688284014ae has not been tested. I've made some attempts to test this, but been having trouble recompiling ulauncher(any version) for unrelated reasons, which I'm still looking into.

@RedBearAK 
> Does it not work to just use a custom Cinnamon shortcut to run ulauncher-toggle?
no

>As long as you avoid using a remapped shortcut combo there should be no focus issue.
yes, but since I've been using Command+Space to access Alfred on mac for 10+ years, I'm not really looking to change that

@friday 
I wasn't really suggesting as a  fix; however, it does work, always. I haven't had any problems since I implemented that patch back in April. Given a Gen4 NVMe SSD the delay is around 1-2 seconds.

**Comment by RedBearAK** [comment] 2022-10-31 14:23
@Sandro0000 

>> As long as you avoid using a remapped shortcut combo there should be no focus issue.
> yes, but since I've been using Command+Space to access Alfred on mac for 10+ years, I'm not really looking to change that

Seems like there's a misunderstanding. I use Cmd+Space myself, and I wouldn't want to use a different one, since that's been the shortcut for Spotlight for as long as it's been around. I just disabled the remap for it in the config of my keyboard remapper (Kinto/xkeysnail, or Kinto/keyszer), which by default remaps Ctrl+Space to Alt+F1 for some reason, and set up Ctrl+Space instead as a custom shortcut in the GNOME keyboard settings that runs the command `ulauncher-toggle`. 

Running the command this way with a custom shortcut makes it unrelated to the keybinding shortcut in Ulauncher's preferences. That also works, once the remap is disabled in the Kinto config file. But the benefit of using custom GNOME shortcuts is that I can set up two different shortcuts (Ctrl+Space and Alt+Space) that both do the same thing, so Ulauncher shows up the same way with the same physical keys whether my keyboard remapper is enabled or disabled. 

Under these circumstances, I have my Ulauncher preferences set to use a different random shortcut that never gets activated directly. 

>> Does it not work to just use a custom Cinnamon shortcut to run ulauncher-toggle?
> no

I don't get this. 

Cinnamon DE has the ability to assign up to three different key combos to the same shortcut entry, which is kind of unusual. I just tried it in a VM with Linux Mint Cinnamon and had no problem setting up a custom shortcut. I get the same focus issue in Mint if I let Kinto remap Ctrl+Space to Alt+F1, but with a custom shortcut that just runs `ulauncher-toggle` there's no focus issue. 

But, maybe Input Remapper works differently.

**Comment by friday** [comment] 2022-10-31 15:31
@RedBearAK It doesn't matter how you bind the keyboard command to trigger the `ulauncher-toggle` command. That's not what the issue is. The issue is that the window manager doesn't want to give focus to the window.

Although, I should say it normally works for me when I'm only on one screen and in X11. I'm able to replicate this when I have certain apps (like gnome-control-center) are in focus and my mouse is on the other screen when I launch Ulauncher.

**Comment by RedBearAK** [comment] 2022-11-13 03:49
@friday 

> It doesn't matter how you bind the keyboard command to trigger the ulauncher-toggle command. That's not what the issue is.

I actually think there is more than one thing going on here, such that we are both technically correct (the best kind of correct). In my case, the culprit is definitely `evdev`, or the keymapper Python app that is using `evdev` to transform some key combos into other key combos. If I bypass this, there is really no problem (for me) with keyboard focus. But then, I don't normally work with multiple monitors. 

In other words, I've confirmed my problem is basically external to Ulauncher, and also affects a few other windows that aren't related to Ulauncher. 

I can see how it might seem that I was saying there would never be a focus problem if you bypass the keymapper with a direct shortcut, but that's not what I intended to convey. There do seem to be other circumstances where Ulauncher fails to acquire focus. As you've described. I was thinking more about the fact that the other poster was also using an app that uses `evdev` to remap input, just like I am. So that's probably the primary cause of their issue.

**Comment by troycurtisjr** [comment] 2022-11-28 01:26
I can definitely confirm that I'm not getting focus after updating my v6 branch. If I restore the `wmctrl` command after the `gdbus call` in `ulaunch-toggle`, then I consistently get focus again. Do we think that #1151 will fix the issue once implemented?

**Comment by friday** [comment] 2022-11-28 16:00
> I can definitely confirm that I'm not getting focus after updating my v6 branch. If I restore the `wmctrl` command after the `gdbus call` in `ulaunch-toggle`, then I consistently get focus again. Do we think that #1151 will fix the issue once implemented?

I think #1151 will solve the "Ulauncher shows on the wrong screen" issue, but I'm afraid we might need to go the full route of closing the application (as indicated by Sandro) to solve the focus issue.

I don't fully understand why this is happening. Is it a Wayland thing? For me it almost never happens (see post above). I have a gnome shell extension to disable gnome's broken focus stealing behavior though.

**Comment by bonds** [comment] 2022-12-28 15:38
My hacky workaround for this issue on pop_os 22.04 and Gnome:

1. Install [Super Key](https://extensions.gnome.org/extension/5188/super-key/), a Gnome extension.
2. Map the super key, in the Super Key extension settings, to 'xdotool keydown Ctrl key space keyup Ctrl' which is to say, [simulate pressing the keys](https://superuser.com/questions/585398/sending-simulated-keystrokes-in-bash) that match the default Ulauncher keyboard shortcut.
3. Profit!

Without that workaround, when I press the Super key Ulauncher pops up, but it doesn't have focus. With that workaround, Ulauncher has focus when I press the Super key, which is of course what I want.

**Comment by friday** [comment] 2023-01-10 00:26
I discovered that the reason it's been working for me is that I had installed an extension disabling focus stealing prevention. I use "Unite", which does a lot more than that, but there are also standalone ones like https://extensions.gnome.org/extension/1005/focus-my-window/.

So if you're on Gnome you have a couple of options now. Other DEs probably have other ways.

This doesn't mean we've given up on trying to solve this. Just lack the time.

**Comment by RedBearAK** [comment] 2023-01-10 01:42
@friday 

> I discovered that the reason it's been working for me is that I had installed an extension disabling focus stealing

OK, so I looked into this for my case (where the problem only occurs for shortcuts that are being translated through a keymapper utility) and this is what I found so far. I already had an extension installed to get rid of the obnoxious "Your window is ready" notification, and automatically focus the new window. It's "NoAnnoyance v2", and it usually works to focus new windows. But perhaps it doesn't actually disable the entire "focus stealing prevention" feature. It seemingly has never had any effect on this issue with Ulauncher. 

I know the "Unite" extension is pretty popular, but I don't like some of the default settings and so I don't usually install it or having it enabled. So I looked for other standalone extensions. 

The one you mentioned, "Focus My Window", doesn't claim to be compatible with any 40/41/42/43/4x versions of GNOME, although one reviewer seems to say it works in "4.3", which is a common mistake when referring to a GNOME 4x version. It may work if the config file is manually updated to allow it to activate in GNOME 4x versions. But in the Extension Manager application it is just listed as "Unsupported" for me, on Fedora 36 with GNOME 43.x. So I would recommend something else. 

I found another standalone extension that is supposed to be for window focus, called "Grand Theft Focus" by zalckos. That one installed with no issue, and it seems to bypass the focus problem. :tada: :tada: :tada: 

I made sure to go through the process of re-enabling the translated shortcut in the keymapper config, disabling the custom shell shortcut that calls  `ulauncher-toggle`, and re-enabling the intended direct shortcut in Ulauncher preferences. So I'm definitely back to calling the Ulauncher dialog directly in the normal way, where I was experiencing this issue. Yet I can't get the focus issue to show up now. Even while I'm using a terminal window, which was always where it had the worst behavior. 

As always, this means when I press the physical Alt+Space keys on my keyboard, the modifier keys have been remapped and so the keymapper takes the resulting Ctrl+Space key codes it sees and translates them yet again into Alt+F1, which activates the Ulauncher window after setting it to respond to Alt+F1. No problem so far. 

Side note: Looks like the focus stealing prevention doesn't necessarily automatically come back on if you just turn off the "Grand Theft Focus" extension, but the focus problem definitely came back after I disabled the extension and then restarted the GNOME shell (with the Alt+F2, R trick). Turning the extension back on then made the problem go away again. 

So I consider that another confirmation that this is an effective workaround for this issue.

**Comment by qcasey** [comment] 2023-03-08 01:41
> I found another standalone extension that is supposed to be for window focus, called "Grand Theft Focus" by zalckos. That one installed with no issue, and it seems to bypass the focus problem. 

Thanks for that! I can also confirm the "Grand Theft Focus" fixes this issue.

**Comment by friday** [comment] 2023-08-13 18:01
This is actually fixed now in v6,but for v5 you still need something like Grand Theft Focus. Leaving it open for now so people will find the workaround

**Comment by friday** [comment] 2023-10-30 21:28
Since the pre-release is out now and fixes this issue for all the DEs I tested at least, I will now close this issue.

**Closed by friday** 2023-10-30 21:28 UTC
Labels: bug
