### ISSUE TITLE
Settings not displaying when Hardware acceleration is deactivated

### ISSUE THREAD

**Issue by Agterra** [Ulauncher/Ulauncher#1109] opened 2022-08-17 08:37 UTC
### Environment

Linux Mint - Kernel 5.15.0-46-generic - i5 1240P - No discrete GPU

### Bug description

# Context

I was having issue with some electron apps recently, hardware acceleration was causing GUI "seizures" with blinking elements and such. I've deactivated Hardware Acceleration globally by creating a `disable-hardware-acceleration.conf` file at `/etc/X11/xorg.conf.d/` containing:

```
Section "Extensions"
    Option "GLX" "Disable"
EndSection
```
And since then, I had no more issues with vscode, slack, discord, ...

# Problem

ULauncher search bar still works fine, but when I click on the cogwheel, the settings windows is displayed but invisible, I can only see the window border's shadow so I know it's there.

# Temporary solution

I've re-enabled hardware acceleration but removing the configuration file from xorg.conf.d and the settings window displays correctly now.

# Question

What could be done to make the settings view work while Hardware Acceleration is disabled ?

Regards.

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Ulauncher v6

- [X] I have made sure the bug isn't already fixed in v6.

**Comment by friday** [comment] 2022-08-17 09:28
It seems like you have the exact opposite problem as #114 then? We use gtkwebkit to render the settings rather than Electron

**Comment by friday** [comment] 2023-04-09 13:55
Closing due to lack of answer/likely duplicate of #114

**Closed by friday** 2023-04-09 13:55 UTC
Labels: bug
