### ISSUE TITLE
using app and accessing preference issues on Ubuntu 20.10

### ISSUE THREAD

**Issue by bot19** [Ulauncher/Ulauncher#673] opened 2021-01-10 00:46 UTC
### Steps to reproduce
1. open app
2. use short-cut (mine ctrl-space to launch)
3. try to open preferences

### Current behavior
- on first app open, shortcut launches app - working as expected
- try to open preferences, but preferences can't be viewed (either all white, or transparent, but likely rendering issue as you still can engage with settings if you know their location, ie: I can still close the window by clicking top-right. See below)
- close app, open again, now shortcut won't launch app anymore

Preferences not visually rendering
![Screenshot from 2021-01-10 10-29-53](https://user-images.githubusercontent.com/24539964/104111667-d7479a00-5338-11eb-838f-01b65d460010.png)

### Expected behavior
- should be able to see preferences
- should be able to launch app even after closing and re-opening app

### Environment
**Ulauncher version**: ulauncher_5.9.0_all.deb
**Linux distro**: Ubuntu 20.10 (64 bit; GNOME 3.38.1; Wayland for windowing system)
**Desktop environment**: ?

### Logs
https://gist.github.com/bot19/b2b3c913a28b5fe73c338e3a37b0b3f6

**Comment by bot19** [comment] 2021-01-10 01:12
Ok, read up about [Ubuntu on Wayland](https://askubuntu.com/questions/1138155/ubuntu-on-wayland) and logged out, logged back in using just "Ubuntu", which seems to use X11 for windowing system. This seems to have fixed everything.

I also noticed in the ulauncher logs that it uses Wayland compatibility mode, which may be where these issues came from. I'll leave this open for a little bit more in case any one had questions. Thanks!

**Comment by ChobotX** [comment] 2021-01-14 08:50
I'm having same issue (environment matches). But Wayland fixed other issues I had so switching back to xorg is not an option for me.

I have also noticed that shortcut (ctrl + space) ain't launching app while on desktop/files/terminal, but if there is any other window active (browser, IDE, anything not built-in) it works (not the preferences, just the launcher).

**Comment by stephane-klein** [comment] 2021-03-23 22:00
@bot19 @ChobotX fixed with https://github.com/Ulauncher/Ulauncher/issues/114#issuecomment-805294594

**Comment by friday** [comment] 2021-10-04 20:52
Closing as a duplicate of #114.

**Closed by friday** 2021-10-04 20:52 UTC
Labels: bug
