### ISSUE TITLE
Slow Reaction / Opening on initial first search on all ULauncher versions above 5.6.1

### ISSUE THREAD

**Issue by leirbag28** [Ulauncher/Ulauncher#686] opened 2021-01-24 22:52 UTC
Starting this report that I previously emailed you about. That every version above 5.6.1 starts at a slow reaction.. 5.6.1 itself works instantaneously and more speedy than all the newest versions...at least on the first try.

**Steps to reproduce:**
_your steps to reproduce here_

**Ulauncher 5.6.1**:
**Ubuntu 18.04.5 LTS 64 bit**:
**MATE 1.20.1**:

**Logs**:

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* https://gist.github.com/leirbag28/c6c935c720a3f2f9c2b71f8c0aa90964

**Comment by gornostal** [comment] 2021-02-07 14:59
Hi @leirbag28 
Thanks for reporting this issue.
You've attached logs from 5.6.1, which as you are saying, works fast enough.
Could you also attach logs from running slow versions? Preferable the latest version: 5.9.0.

**Comment by leirbag28** [comment] 2021-02-08 15:20
Interesting thing happened...but now 5.6.1 reacts slow to open in the first try like all the newer versions...so I went down to 5.6.0 which works fast immediately...i didn't want to go further down because I remember an issue you fixed (dont remember which version) in which nothing would show up when I typed to search....but anyway 5.6.0 is working fine so far and I will send you the logs for both 5.6.0 and 5.9.0

**Comment by gornostal** [comment] 2021-02-08 19:38
Yeah, it will be very interesting to see logs from 5.9.0. 
Just please make sure the logs include a time frame where you felt that slow response.

If you open the logs you've attached, you'll see the time diff between the first and the last log entry is 316ms. So far I didn't see anything slow there :)

**Comment by leirbag28** [comment] 2021-02-09 00:09
Maybe "slow" is the wrong terminology....its more of a delayed reaction when you press CTRL + SPACE to open it and start typing...it doesn't respond (5.6.1 and up) as snappy as 5.6.0.....after that first time on boot pressing CRTL + SPACE (ei: the second time, and third and fourth and so on) it works perfect. Its almost like 5.6.0 just loads up fully and tests itself....I don't know....but you might :-)

**Comment by friday** [comment] 2021-08-13 14:29
Duplicate of #693. It's better to have one tracking issue for this even if it affects multiple Ulauncher versions.

**Closed by friday** 2021-08-13 14:29 UTC
