### ISSUE TITLE
Plans for more/3rd party themes?

### ISSUE THREAD

**Issue by IgnusG** [Ulauncher/Ulauncher#140] opened 2017-07-03 12:49 UTC
Any plans to support themes? 
I currently experience a small ui glitch with the settings button in both currently available themes.

![Settings button](http://i65.tinypic.com/24wei9v.png)
It looks as if 2 buttons are rendered with the second one being cut off on the side...

**Comment by gornostal** [comment] 2017-07-04 04:40
3rd party themes will be the next milestone. Current is extensions.

What's your Ulauncher version, Linux distro, and desktop environment?

**Comment by IgnusG** [comment] 2017-07-04 07:04
Great!

LD: Arch
Ulauncher: 2.2.1.r0-1 (ulauncher AUR)
DE: deepin-desktop-environment

**Comment by gornostal** [comment] 2017-07-05 12:20
@IgnusG this is a duplicate of #107 
Please subscribe to updates in that ticket.

**Closed by gornostal** 2017-07-05 12:20 UTC
