### ISSUE TITLE
Search bar opening flicker

### ISSUE THREAD

**Issue by Colanderr** [Ulauncher/Ulauncher#547] opened 2020-04-19 08:20 UTC
About 50 % of the time when opening the launcher, the search bar appears in the center of the screen and a few frames later it moves to the correct position, which is a bit higher. I think it happens more often when I search for something, close the launcher and then open it again.

Video:
![flicker](https://user-images.githubusercontent.com/11477797/79683014-491a0980-8227-11ea-98a4-5e41784e4392.gif)

**Steps to reproduce:**
1. open the launcher
2. type in something so that there are some results
3. close the launcher
4. open it again

**Ulauncher version**: 5.7.4
**Linux distro**: Linux Mint 19.3
**Desktop environment**: Cinnamon

**Logs**:
https://gist.github.com/Colanderr/28950d8e49992b8ce06340bf17233d6d

**Comment by troycurtisjr** [comment] 2020-11-21 14:58
This seems like it might be related to #632

**Comment by Colanderr** [comment] 2020-11-24 20:48
@troycurtisjr I don't think so, that one seems to happen in a different stage - when searching, not when starting the launcher application. But I honestly have no idea about the inner workings of the launcher.

As a side note, (mainly) because of this issue I switched to Rofi, no longer use Ulauncher and the system this happened on is no longer in operation, so a fix would be hard to test if there is nobody else is affected.

**Comment by friday** [comment] 2021-12-07 23:11
Closing as a duplicate of #911 (which is probably a GTK3 issue fixed by upgrading to GTK4). Either way this issue is not something we can reproduce, nor fix. The Ulauncher window is open the whole time, and the issue is entirely graphical, happening on a lower layer library (GTK, X11 or the gpu drivers).

**Closed by friday** 2021-12-07 23:11 UTC
