### ISSUE TITLE
Ulauncher Extensions URL Error

### ISSUE THREAD

**Issue by eMSiBi** [Ulauncher/Ulauncher#292] opened 2018-09-23 13:22 UTC
**Steps to reproduce:**
1) Open Ulauncher
2) Open Ulauncher Settings->Extensions->Add Extension
3) Add any extension

Note: I don't have any firewall, clean install of Deepin and i can access/download to the extension link on browser. 

**Ulauncher version**: Ulauncher version 4.3.0.r2
**Linux distro**: DeepinOS 15.7
**Desktop environment**: DDE

**Logs**: [Logs](https://gist.github.com/eMSiBi/a2d8428d4bda4f1372fe7d7f235e46c8)
Also have different os logs at this [link](https://github.com/Ulauncher/Ulauncher/issues/277#issuecomment-417956353)

**Comment by friday** [comment] 2018-09-23 16:27
Did you paste the full github url, not just the user/repo-part?

**Comment by eMSiBi** [comment] 2018-09-23 18:14
> Did you paste the full github url, not just the user/repo-part?
> 
> Answering my own question, the log says "Add extension: https://github.com/brpaz/ulauncher-chrome-tabs"

Tried others too but got same error.

**Comment by gornostal** [comment] 2018-10-02 17:42
Hi @eMSiBi 
I've improved logging in v4.3.1.r4. Could you try a new version and attach the new logs please?

In the logs you've attached it's not clear why request to download the extension was failing.

**Comment by eMSiBi** [comment] 2018-10-02 18:53
There [it is](https://gist.github.com/eMSiBi/c22afe200bcc69ca2cf6163b38affc6d) :crossed_fingers:

**Comment by gornostal** [comment] 2018-10-02 19:07
> URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)>

This looks like someone (maybe even you) configured your network to spoof SSL Certificates (request to 
get the extension goes through an intermediate server, which may decrypt and analyze your "encrypted" traffic).
Security considerations aside, in order to fix that you can install a root certificate (that you can obtain from your network admin) into your system: https://askubuntu.com/questions/645818/how-to-install-certificates-for-command-line/859887

_Maybe I'm wrong about the root cause, but I had exactly the same issues in company that I worked and I had to install a new root cert._

**Comment by eMSiBi** [comment] 2018-10-02 19:17
The interesting and bad news is i dont modified my ssl stuff and its scares me because of your said. Its a home network and i know all devices that connected my network. t shoudn't be like that, am i wrong?

**Comment by gornostal** [comment] 2018-10-02 19:27
Try `curl https://github.com`
If it doesn't work, then something is wrong with your network.

**Comment by eMSiBi** [comment] 2018-10-02 19:30
It [works](https://gist.github.com/eMSiBi/04610dbb3f5f26082845e59412016171) actually, and also i know that at different OS, Ulauncher Extensions are worked for once.

**Comment by gornostal** [comment] 2018-10-02 19:30
> it shoudn't be like that, am i wrong?

No, you're not wrong.

**Comment by gornostal** [comment] 2018-10-03 03:53
hmm If curl works then I don't know what could cause that issue 🤔

**Comment by gornostal** [comment] 2018-12-22 19:46
Hi @eMSiBi 
I'm closing this one.
If you need more help with this issue please reopen.

**Closed by gornostal** 2018-12-22 19:46 UTC
Labels: bug, severity-high, size-S
