### ISSUE TITLE
Allow the use of different Decimal Separators

### ISSUE THREAD

**Issue by astroty** [Ulauncher/Ulauncher#786] opened 2021-08-21 20:33 UTC
Hello, I come here to ask about the possibility of using a different decimal separator with the program. This characteristic is usually tied to the language in most programs but in Ulauncher it seems to be hard coded to only accept dot, which introduces a roadblock for places that use other separators.

**Comment by friday** [comment] 2021-08-22 08:10
Duplicate of #575

**Closed by friday** 2021-08-22 08:10 UTC
