### ISSUE TITLE
Wish: Add to documentation: Hint about desktop entries indexing

### ISSUE THREAD

**Issue by kstenschke** [Ulauncher/Ulauncher#305] opened 2018-10-04 15:27 UTC
First of all thankyou very much for your efforts on ulauncher, i am happy to have finally found what looks at the moment like the best linux application launcher to me :+1: 
IMO the 3 features that make ulauncher the perfect tool, are shortcuts, the extension system AND that desktop entries in ~/.local/share/applications/ are indexed as applications.

The documentation at the ulauncher website, github and http://docs.ulauncher.io/en/latest/index.html should IMO really contain at least a short hint about desktop entries.

**Comment by friday** [comment] 2018-10-18 16:08
> please go ahead fork it, and submit a PR with the changes you think are needed and we can consider them

I think this was well intended as a pointer to where to make the change, but the formulation was somewhat coercive and unfortunate. Forking and submitting PR's is great, and while the possibility could be presented, it should not be *expected* from people creating issues imo. Creating the issue is a contribution in the first place.

**Comment by gornostal** [comment] 2018-10-20 20:10
> First of all thankyou very much for your efforts on ulauncher, i am happy to have finally found what looks at the moment like the best linux application launcher to me +1

I'm happy to hear that :smiley: 

Since #308 is resolved I'm going to close this issue too.

**Closed by gornostal** 2018-10-20 20:10 UTC
