### ISSUE TITLE
search window hides when keyboard layout changes

### ISSUE THREAD

**Issue by ottotis** [Ulauncher/Ulauncher#676] opened 2021-01-12 18:27 UTC
### Steps to reproduce
1. Open search window (Ctrl+Space)
2. Change layout (Alt+Shift for example)
3. Window closes

### Current behavior
Window closes after keyboard layout changing. If I have shortcut to change layout - Alt+Shift, then window closes after Alt+Shift. Ctrl+Shift does nothing. If I change shortcut to Ctrl+Shift, then it closes at Ctrl+Shift, but Alt+Shift does nothing. So I can not use second language at all

### Expected behavior
Search window stays open and lets me keep typing in another layout

### Environment
**Ulauncher version**: 5.9.0-1
**Linux distro**: Manjaro rolling
**Desktop environment**: GNOME 3.38.2

### Logs

In logs no happens (no new lines appear). Seems like it just normally hides search window when keyboard layout changes.

**Comment by ottotis** [comment] 2021-01-13 16:42
solved.

../ulauncher/ui/windows/UlauncherWindow.py:154

changed timer from 0.07 to 0.15

t = threading.Timer(0.15, lambda: self.is_focused or self.hide())

**Comment by gornostal** [comment] 2021-01-20 19:48
Closing as a duplicate of #635

**Closed by gornostal** 2021-01-20 19:48 UTC
