### ISSUE TITLE
crashing as soon as i save in linux mint 

### ISSUE THREAD

**Issue by gfborges** [Ulauncher/Ulauncher#448] opened 2019-10-09 22:57 UTC
### Steps to reproduce
1. Install
2. Save
3.

### Current behavior
Crashing

### Expected behavior
?

### Environment
**Ulauncher version**: v 5.3.0
**Linux distro**: Linux Mint  (19.2)
Linux ada 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Desktop environment**:
Cinnamon
### Logs 

/usr/lib/python3/dist-packages/ulauncher/main.py:8: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk

Message: 'com.github.pbkhrv.ulauncher-zeal'
Error Name: UnhandledError
Type: KeyError
Stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 411, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.pbkhrv.ulauncher-zeal'

```

**Comment by friday** [comment] 2019-11-16 21:48
This is almost certainly a duplicate of #273. Misleading/confusing that it happens during install, but it's actually a missing dependency in the extension (which has been deleted now it seems).

**Comment by gornostal** [comment] 2019-11-18 06:07
I can't find `ulauncher-zeal` extension on Github.

@gabrielfrborges could you clarify steps to reproduce, please?

It's not clear what you are trying to install or save. Ulauncher or extension? What extension?

Thanks

**Comment by friday** [comment] 2021-08-12 12:25
Closing this. See #767

**Closed by friday** 2021-08-12 12:25 UTC
Labels: bug
