### ISSUE TITLE
.desktop "NotShowIn" support

### ISSUE THREAD

**Issue by ryanerwin** [Ulauncher/Ulauncher#343] opened 2019-02-08 08:30 UTC
**Steps to reproduce:**
Edit a file like: `~/.local/share/applications/xfce4-terminal.desktop`
Add an entry like: `NotShownIn=GNOME;KDE`

**Ulauncher version**: v4.3.1r4
**Linux distro**: Arch Linux
**Desktop environment**: Gnome

The `NotShownIn` setting is documented here:

https://wiki.archlinux.org/index.php/Desktop_entries#Hide_desktop_entries

> To hide the entry in a specific desktop, add the following line to the desktop entry file: 
> `NotShowIn=desktop-name`
>
> where desktop-name can be option such as GNOME, Xfce, KDE etc. A desktop entry can be hidden in more than desktop at once - simply separate the desktop names with a semi-colon.

If I understand correctly, Ulauncher is using Python gio to parse .desktop files, and Python's gio does have support for the `NotShownIn` field:

https://developer.gnome.org/gio/stable/gio-Desktop-file-based-GAppInfo.html#g-desktop-app-info-get-show-in

I think the relevant code may be: `ulauncher/util/desktop/reader.py`...

**Comment by ryanerwin** [comment] 2019-02-08 08:43
Looks like there's also a `OnlyShowIn` that would be equally useful... And would help immediately in preventing unwanted apps from showing up...

You'll probably see that your current system already has a lot of apps that can be filtered this way:

```bash
grep -r OnlyShowIn /usr/share/applications
```

**Comment by friday** [comment] 2019-02-08 17:16
#334 has some implementation info on this, though it's a very simple change anyway.

**Comment by RedBearAK** [comment] 2021-03-09 22:25
This remains a problem in 2021. This really needs to be fixed because it can cause major confusion for the end user. Even with the descriptions on display, there is no way to tell these different applications apart, and they each only apply settings to one specific desktop environment. 

![onlyshowin_ulauncher](https://user-images.githubusercontent.com/64876997/110545502-ab972500-80d9-11eb-8960-409d177ff270.png)

Albert launcher is doing this correctly: 

![onlyshowin_albert](https://user-images.githubusercontent.com/64876997/110545894-3d069700-80da-11eb-851f-f217c9a01da6.png)

**Comment by friday** [comment] 2021-07-02 21:19
This has been fixed in my fork: https://github.com/friday/Ulauncher-Revived

No supported distros besides Arch yet.

**Comment by friday** [comment] 2021-08-20 17:42
This is now supported in 5.12.0 (just released).

**Closed by friday** 2021-08-20 17:42 UTC
Labels: enhancement, contributor-friendly, Python

**Comment by jtheoof** [comment] 2021-09-05 19:27
@friday This is causing a few side effects (for me). I'm running [sway](https://github.com/swaywm/sway) which sets: 

```
❯ echo $XDG_CURRENT_DESKTOP
sway
```

With this patch, all the gnome applications are now filtered out by the `filter_app` function. I understand that this is the intended behavior based on #343 but gnome applications can be quite useful in a sway environment.

Would it be possible to make the filter a bit more configurable. Like adding `show-apps-in-env=sway;gnome;kde` in `settings.json`?

**Comment by friday** [comment] 2021-09-05 19:38
@jtheoof: Not sure thst's something I want to add, but you can set custom environment variables before running ulauncher

* If you use systemd: https://github.com/Ulauncher/Ulauncher/issues/780#issuecomment-912982174
* If you don't, you can copy the `/usr/share/applications/ulauncher.desktop` to `~/.local/share/applications/` and modify the `Exec` line to add your environment variables.

**Comment by friday** [comment] 2021-09-05 19:42
And could you make a separate issue for this so it's easier to remember and we don't message people who subscribed to this issue @jtheoof? I don't want to reopen this issue.
