### ISSUE TITLE
Unable to install on Fedora 32

### ISSUE THREAD

**Issue by mjj55409** [Ulauncher/Ulauncher#607] opened 2020-08-19 20:02 UTC
**Steps to reproduce:**
sudo dnf install ulauncher_5.8.0_fedora.rpm

It fails with the error: nothing provides python(abi) = 3.7 needed by ulauncher-5.8.0-1.noarch

**Ulauncher version**: 5.8.0
**Linux distro**: Fedora 32
**Desktop environment**: Gnome 3.36.4 (Wayland)

**Logs**:

_To get the logs please do the following:_
_* Close the app_
_* Run "ulauncher -v" from the console_
_* Copy output to https://gist.github.com/_
_* Link to the gist here_

**Comment by pgqz53** [comment] 2020-08-30 18:32
https://src.fedoraproject.org/rpms/ulauncher

Just do `dnf install ulauncher` instead.

**Comment by StefKors** [comment] 2020-09-16 10:49
@pgqz53 the `dnf` version looks broken, the settings menu doesn't work (blank screen) and it's super buggy. Any other suggestions?

**Comment by benfrain** [comment] 2020-09-19 17:31
Same issue, followed instructions from front page and got the same `nothing provides python(abi)` message as @mjj55409

**Comment by NoxHarmonium** [comment] 2020-10-31 08:49
The latest RPM on the releases only supports Python < 3.8
This means it won't work on Fedora 32 and 33 because they use Python 3.8 and 3.9 respectively.

The good news is that it is easy to build locally once you update the `mypy` package.

If you update requirements.txt so that mypy is version "0.790" and mypy_extensions is version "0.4.3" it seems to build and work fine.

I've uploaded a patch here that you can apply to the current version of the code base.

https://gist.github.com/NoxHarmonium/2f9d3fd70b587422051206a96f04667d

Then just run:

```bash
pip3 install -r requirements.txt
./ul build-preferences
source /etc/os-release
./ul build-rpm 5.8.1-fc${VERSION_ID} fedora fc${VERSION_ID}
sudo rpm install /tmp/ulauncher_5.8.1-fc${VERSION_ID}_fc${VERSION_ID}.rpm
```

Although you might need to install some python dependencies first

```
sudo dnf groupinstall "Development Tools"
sudo dnf install python3-distutils-extra python3-devel
```

I've attached a zipped RPM that I built on f33 (I don't think it will work on f22). It seems to work for me but use at your own risk!

[ulauncher_5.8.1-fc33_fc33.zip](https://github.com/Ulauncher/Ulauncher/files/5468782/ulauncher_5.8.1-fc33_fc33.zip)

I suppose the better long term solution is to get those version bumps merged into the main code base and get the CI/CD builder running on a later version of Fedora. I'm not a python developer so I'm not sure what side effects we will get from bumping those versions. I'll have to do some reading and maybe raise a PR if I'm confident I'm not going to break anything.

**Comment by troycurtisjr** [comment] 2020-11-21 15:38
Just a note that the latest version in the Fedora 32 repos appears to be working, so you might try with `dnf` again.

**Comment by gornostal** [comment] 2020-11-22 20:18
I can confirm, it works fine for Python 32.
However, I updated release process a bit: now RPM build for Fedora 32 an below appears without any suffix on ulauncher.io
Fedora 33 build has `fedora33` in the name however.
Closing this one.

**Closed by gornostal** 2020-11-22 20:18 UTC
