### ISSUE TITLE
Preferences screen is just a white box

### ISSUE THREAD

**Issue by lighttigerXIV** [Ulauncher/Ulauncher#995] opened 2022-03-24 11:02 UTC
### Environment

EndeavourOS Linux x86_64, KDE

### Bug description

When i go to preferences i just get a white box. 
I don't know if i am missing a dependency What could it be.
I tried cleaning the config files and reinstalling but nothing worked. 

Here is an image:
![image](https://user-images.githubusercontent.com/35658492/159902705-836fb3e6-9b1d-4085-99ab-41d5899dc191.png)

### Log output

```shell
2022-03-24 10:59:25,013 | INFO | ulauncher: main() | Ulauncher version 5.14.3
2022-03-24 10:59:25,013 | INFO | ulauncher: main() | Extension API version 2.0.0
2022-03-24 10:59:25,013 | INFO | ulauncher: main() | GTK+ 3.24.33
2022-03-24 10:59:25,013 | INFO | ulauncher: main() | Is Wayland: False
2022-03-24 10:59:25,014 | INFO | ulauncher: main() | Wayland compatibility: off
2022-03-24 10:59:25,033 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2022-03-24 10:59:25,035 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2022-03-24 10:59:25,035 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2022-03-24 10:59:25,035 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2022-03-24 10:59:25,035 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2022-03-24 10:59:25,036 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2022-03-24 10:59:25,036 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2022-03-24 10:59:25,036 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2022-03-24 10:59:25,036 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2022-03-24 10:59:25,036 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2022-03-24 10:59:25,037 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2022-03-24 10:59:25,037 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2022-03-24 10:59:25,042 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-03-24 10:59:25,043 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2022-03-24 10:59:25,043 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2022-03-24 10:59:25,055 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.tjquillan.ulauncher-system" started. PID 18700
2022-03-24 10:59:25,056 | INFO | ulauncher.api.server.ExtensionRunner: _run_process() | Extension "com.github.hoaper.ulauncher-zh0per" started. PID 18702
2022-03-24 10:59:25,062 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 81 apps in cache
2022-03-24 10:59:25,064 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/home/lighttigerxiv/.local/share/applications/userapp-Nightly-MQ8KJ1.desktop": constructor returned NULL
2022-03-24 10:59:25,064 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/home/lighttigerxiv/.local/share/applications/open-in-mpv.desktop": constructor returned NULL
2022-03-24 10:59:25,064 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/home/lighttigerxiv/.local/share/applications/google-chrome.desktop": constructor returned NULL
2022-03-24 10:59:25,065 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/home/lighttigerxiv/.local/share/applications/firefox-nightly.desktop": constructor returned NULL
2022-03-24 10:59:25,065 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/home/lighttigerxiv/.local/share/applications/mpv-handler.desktop": constructor returned NULL
2022-03-24 10:59:25,066 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_kimgio.desktop": constructor returned NULL
2022-03-24 10:59:25,067 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_plucker.desktop": constructor returned NULL
2022-03-24 10:59:25,068 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.kdeconnect_open.desktop": constructor returned NULL
2022-03-24 10:59:25,069 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_md.desktop": constructor returned NULL
2022-03-24 10:59:25,070 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_chm.desktop": constructor returned NULL
2022-03-24 10:59:25,070 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_fb.desktop": constructor returned NULL
2022-03-24 10:59:25,070 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_mobi.desktop": constructor returned NULL
2022-03-24 10:59:25,071 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_pdf.desktop": constructor returned NULL
2022-03-24 10:59:25,071 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_epub.desktop": constructor returned NULL
2022-03-24 10:59:25,073 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_tiff.desktop": constructor returned NULL
2022-03-24 10:59:25,073 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_xps.desktop": constructor returned NULL
2022-03-24 10:59:25,074 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_txt.desktop": constructor returned NULL
2022-03-24 10:59:25,075 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_dvi.desktop": constructor returned NULL
2022-03-24 10:59:25,075 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.kded5.desktop": constructor returned NULL
2022-03-24 10:59:25,076 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_comicbook.desktop": constructor returned NULL
2022-03-24 10:59:25,076 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_fax.desktop": constructor returned NULL
2022-03-24 10:59:25,078 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.kwin_rules_dialog.desktop": constructor returned NULL
2022-03-24 10:59:25,081 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_ghostview.desktop": constructor returned NULL
2022-03-24 10:59:25,081 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/org.kde.mobile.okular_djvu.desktop": constructor returned NULL
2022-03-24 10:59:25,085 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 81 apps in the system
2022-03-24 10:59:25,085 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.04 seconds
2022-03-24 10:59:25,086 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
2022-03-24 10:59:25,089 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2022-03-24 10:59:25,181 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.hoaper.ulauncher-zh0per" connected
2022-03-24 10:59:25,182 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.hoaper.ulauncher-zh0per"
com.github.hoaper.ulauncher-zh0per | 2022-03-24 10:59:25,182 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-03-24 10:59:25,206 | INFO | ulauncher.api.server.ExtensionController: handleConnected() | Extension "com.github.tjquillan.ulauncher-system" connected
2022-03-24 10:59:25,207 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event PreferencesEvent to "com.github.tjquillan.ulauncher-system"
com.github.tjquillan.ulauncher-system | 2022-03-24 10:59:25,207 | DEBUG | ulauncher.api.client.Client: on_message() | Incoming event PreferencesEvent
2022-03-24 10:59:29,255 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2022-03-24 10:59:29,266 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2022-03-24 10:59:29,266 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2022-03-24 10:59:29,320 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2022-03-24 10:59:29,320 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2022-03-24 10:59:29,321 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2022-03-24 10:59:29,322 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2022-03-24 10:59:36,204 | DEBUG | ulauncher.ui.windows.UlauncherWindow: on_preferences_dialog_destroyed() | on_preferences_dialog_destroyed
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines and checked the troubleshooting page for self-help.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment] 2022-03-24 12:50
We used to get tons of these back in the day. I wasn't sure it still happened, but you can find many old issues for this and some have good info.

Also please try the v6 branch if it's fixed there or if you get better debug messages.

Here's how to: https://github.com/Ulauncher/Ulauncher/blob/dev/CONTRIBUTING.md#code-contributions

**Comment by friday** [comment] 2022-03-24 12:53
Duplicate of #114

**Closed by friday** 2022-03-24 12:53 UTC
Labels: bug

**Comment by lighttigerXIV** [comment] 2022-03-24 14:43
> 

Still the same. I have followed the the link you gave me

**Comment by friday** [comment] 2022-03-24 14:49
This means your Python environment is broken or isolated and doesn't load system modules. Can't really debug that from my end unfortunately.

**Comment by lighttigerXIV** [comment] 2022-03-24 15:01
> This means your Python environment is broken or isolated and doesn't load system modules. Can't really debug that from my end unfortunately. :(
> 
> Thanks for trying!

Could it be from anaconda?

**Comment by lighttigerXIV** [comment] 2022-03-24 15:48
I give up XD. What's bothering me is that a few days ago it was working perfectly.

**Comment by friday** [comment] 2022-03-24 15:53
It could be #820 causing the python issues, but there's no simple solution as pyenv is only one such tool.

And see the #114 workaround for the preferences issue.

**Comment by friday** [comment] 2022-03-27 22:02
This package is using v6 now: https://aur.archlinux.org/packages/ulauncher-git

**Comment by lighttigerXIV** [comment] 2022-03-28 09:28
> This package is using v6 now: https://aur.archlinux.org/packages/ulauncher-git

When in installed arch a few days ago it worked flawlessly. I will stop using anaconda and start using venv XD. And v6 is looking great :P

**Comment by nick-robo** [comment] 2022-04-12 13:08
Still bank for me after switching to `ulauncher-git`. 

Running `ulauncher -v` gives the following when opening settings:
<details> 
  <summary>Output</summary>

```
~> ulauncher -v
2022-04-12 14:56:52,809 | INFO | ulauncher: main() | Ulauncher version 6.0.0
2022-04-12 14:56:52,809 | INFO | ulauncher: main() | Extension API version 2.0
2022-04-12 14:56:52,809 | INFO | ulauncher: main() | GTK+ 3.24.33
2022-04-12 14:56:52,809 | INFO | ulauncher: main() | Session type: wayland
2022-04-12 14:56:52,809 | INFO | ulauncher: main() | X11 backend: Yes
2022-04-12 14:56:52,922 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2022-04-12 14:56:52,924 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2022-04-12 14:56:52,924 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2022-04-12 14:56:52,924 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2022-04-12 14:56:52,925 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2022-04-12 14:56:52,925 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2022-04-12 14:56:52,925 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2022-04-12 14:56:52,925 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_destroyed'
2022-04-12 14:56:52,930 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-04-12 14:56:52,933 | DEBUG | ulauncher.modes.extensions.ExtensionServer: start() | Removing existing socket path /run/user/1000/ulauncher_control
2022-04-12 14:56:52,961 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2022-04-12 14:57:01,643 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | Create new preferences window
2022-04-12 14:57:01,677 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2022-04-12 14:57:01,677 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2022-04-12 14:57:01,679 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2022-04-12 14:57:01,680 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
^C2022-04-12 14:57:07,598 | WARNING | ulauncher: main() | On KeyboardInterrupt
```
</details>

![image](https://user-images.githubusercontent.com/17681331/162967774-1ed9b773-4417-4423-92e6-fee6bc643846.png)


# Sysinfo
OS: EndeavourOS Linux x86_64
DE: GNOME 42.0 (xwayland)

**Comment by friday** [comment] 2022-04-12 13:16
Thank you @nick-robo. Are you saying this didn't happen to you in v5, but does in v6. Or in both?

Something must have happened recently because this issue is becoming increasingly common. I don't want to keep too many issues about the same thing, so please subscribe use #1001 for further communication on this and subscribe to that issue to get notified of changes :)

**Comment by nick-robo** [comment] 2022-04-12 13:18
Happened in both @friday.
