### ISSUE TITLE
draw over fullscreen applications instead of minimizing them

### ISSUE THREAD

**Issue by MyriaCore** [Ulauncher/Ulauncher#577] opened 2020-06-25 22:32 UTC
### Is your feature request related to a problem? Please describe

When ulauncher is opened over a fullscreen application, the fullscreen application is minimized. This might not be what the user intends, and might be significantly disruptive, as #513 points out. 

The solution suggested in #513 is to prefer the solution provided by #509, but this wouldn't for all cases. For example, when watching youtube or netflix in fullscreen, the user would be forced to block their entire web browser, so ulauncher doesn't minimize their video. This is a pretty wide net, however, and it's clearly acceptable for ulauncher to launch over a site like github, for example.

### Describe the solution you'd like

Don't force the application to minimize. Instead, draw over the current fullscreen application. 

---

Not 100% sure if this is possible with the tooling / UI libraries that are used in ulauncher. I assume the only reason this happens is due to some technical limitation, or this likely would have been implemented earlier. However, it *is* possible to draw over fullscreen applications. If it weren't, applications like flameshot and slop wouldn't be able to render as they do.

**Comment by friday** [comment] 2020-07-01 14:03
Those other issues you linked to are from users who want the Ulauncher toggle key to be disabled under different circumstances, because they press it, meaning something else in a different app. This is not the issue you're having.

I can't reproduce the issue you're having. If I watch a youtube video in fullscreen or download and watch a video with VLC or Totem toggling Ulauncher doesn't minimize them. They keep playing in fullscreen mode.

Maybe you have some other command that activates when you press ctrl + space?

**Comment by MyriaCore** [comment] 2020-07-01 15:10
You're 100% right, I just tested with chrome and it keeps its fullscreen (despite some i3 wonkyness lol). I'm actually a firefox user, so this issue seems to be upstream.

**Comment by friday** [comment] 2021-08-22 19:46
I'm closing this, since I don't think there's anything Ulauncher does wrong or can do better here.

**Closed by friday** 2021-08-22 19:46 UTC
