### ISSUE TITLE
Window position

### ISSUE THREAD

**Issue by PierfrancescoArdino** [Ulauncher/Ulauncher#205] opened 2018-01-24 08:07 UTC
![screenshot from 2018-01-24 09-02-37](https://user-images.githubusercontent.com/9986725/35320856-9365a3b6-00e5-11e8-8aa7-efbc3d3a4b5a.png)

The position of the window seems wrong, moreover to write a command on the input field I've to first click on it.

I'm not 100% but it seems to happen after launching a second command. Before then, the widget seems to work as expected. 

**Ulauncher version**: Ulauncher-git latest
**Linux distro**: Arch Linux
**Desktop environment**: Gnome on Wayland

**Comment by gornostal** [comment] 2018-01-24 08:10
could you attach logs please?

**Comment by gornostal** [comment] 2018-01-24 08:12
I've seen this issue only when `GDK_BACKEND` is set to `wayland` explicitly.

**Comment by PierfrancescoArdino** [comment] 2018-01-24 08:27
> 2018-01-24 09:19:55,863 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2018-01-24 09:19:55,863 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2018-01-24 09:19:55,864 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2018-01-24 09:20:02,366 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2018-01-24 09:20:02,367 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2018-01-24 09:20:02,367 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2018-01-24 09:20:04,681 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2018-01-24 09:20:04,682 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2018-01-24 09:20:04,682 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2018-01-24 09:20:05,815 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2018-01-24 09:20:05,815 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2018-01-24 09:20:05,816 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2018-01-24 09:20:06,840 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2018-01-24 09:20:06,840 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2018-01-24 09:20:06,841 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2018-01-24 09:20:07,821 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2018-01-24 09:20:07,821 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2018-01-24 09:20:07,822 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2018-01-24 09:20:09,127 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2018-01-24 09:20:09,128 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2018-01-24 09:20:09,128 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results



This is the last part of the log. The first part contains several error regarding pyinotify (I think I have to increase again the Inotify limit). 

I've launched the app using ``` GDK_BACKEND=x11```

**Comment by gornostal** [comment] 2018-01-24 08:29
I actually need beginning of the log.

**Comment by PierfrancescoArdino** [comment] 2018-01-24 08:32
```
GDK_BACKEND=x11 ulauncher -v
/usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib
2018-01-24 09:30:26,088 | INFO | ulauncher: main() | Ulauncher version DEV
2018-01-24 09:30:26,088 | INFO | ulauncher: main() | GTK+ 3.22.26
2018-01-24 09:30:26,088 | INFO | ulauncher: main() | Is Wayland: True
2018-01-24 09:30:26,089 | INFO | ulauncher: main() | Wayland compatibility: off
2018-01-24 09:30:26,103 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2018-01-24 09:30:26,107 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2018-01-24 09:30:26,108 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2018-01-24 09:30:26,108 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2018-01-24 09:30:26,109 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2018-01-24 09:30:26,109 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2018-01-24 09:30:26,109 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2018-01-24 09:30:26,109 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2018-01-24 09:30:26,110 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2018-01-24 09:30:26,110 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2018-01-24 09:30:26,111 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2018-01-24 09:30:26,111 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2018-01-24 09:30:26,116 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2018-01-24 09:30:26,118 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5050
2018-01-24 09:30:26,157 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>p
(ulauncher:4813): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window-update_and_descendants_freeze_count > 0' failed

```

**Comment by gornostal** [comment] 2018-01-24 08:49
hmm nothing unusual

do you have file `~/.config/weston.ini`, if so could you post its content?

**Comment by PierfrancescoArdino** [comment] 2018-01-24 08:51
No, I'm not using weston as Wayland Compositor

**Comment by gornostal** [comment] 2018-01-24 08:54
The issue occurs when ulauncher is not running in X11 compatibility mode. GDK_BACKEND=x11 should have switched that on, but apparently it didn't. Hence weird positioning of the app.

I'll think what we can do...

**Comment by beanaroo** [comment] 2018-01-28 02:15
Not a Wayland user at the moment, but I've had this problem with other "pop-up" applications. Tilix and Tilda drop down terminal emulators, for example. gnunn1/tilix#494

**Comment by gornostal** [comment] 2018-01-28 08:14
@PierfrancescoArdino would it be possible for you to create a VBox image where you can reproduce the bug, and then send it to me?
Even then I'm not sure I will find a solution, but that would definitely be more efficient than trying different things via Github chat.

**Comment by PierfrancescoArdino** [comment] 2018-01-30 09:21
Mmm not that sure (not enough free time) but I will try

**Comment by kevinwung** [comment] 2018-02-23 03:21
Will this program run on Windows?

**Comment by janchk** [comment] 2018-02-25 11:24
@kevinwung No. It's made for Linux. For Windows you must search for alternatives.

**Comment by Shuunen** [comment] 2018-03-30 13:39
@gornostal here a VM https://drive.google.com/open?id=1HYWNuyrfFvO5ftUSaPXUmqu5lQEzY8lG

It's a Linux Mint with ulauncher_4.0.6.r1_all.deb installed & failling

**Comment by gornostal** [comment] 2018-03-30 13:41
Perfect. Thanks a lot @Shuunen

**Comment by Shuunen** [comment] 2018-03-30 13:49
```
chou@choumintou-vm ~ $ ulauncher
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib

(ulauncher:3677): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
^Cchou@choumintou-vm ~ GDK_BACKEND=x11
chou@choumintou-vm ~ $ echo "$GDK_BACKEND"
x11
chou@choumintou-vm ~ $ ulauncher
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib

(ulauncher:3740): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
^CException in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionServer.py", line 52, in _start_thread
    self.ws_server.serveforever()
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/SimpleWebSocketServer.py", line 624, in serveforever
    rList, wList, xList = select(self.listeners, writers, self.listeners, self.selectInterval)
TypeError: 'NoneType' object is not callable
```

**Comment by gornostal** [comment] 2018-03-30 13:51
BTW, what username and root password should I use?

**Comment by Shuunen** [comment] 2018-03-30 13:52
user/pass : chou/chou

**Comment by Shuunen** [comment] 2018-03-30 13:55
Just purge uninstall uLauncher that I installed via deb & installed it via ppa : 
```
Get:1 http://ppa.launchpad.net/agornostal/ulauncher/ubuntu xenial/main amd64 ulauncher all 4.0.6.r1-0ubuntu1ppa1~xenial [1,068 kB]
Fetched 1,068 kB in 0s (2,472 kB/s) 
Selecting previously unselected package ulauncher.
(Reading database ... 201336 files and directories currently installed.)
Preparing to unpack .../ulauncher_4.0.6.r1-0ubuntu1ppa1~xenial_all.deb ...
Unpacking ulauncher (4.0.6.r1-0ubuntu1ppa1~xenial) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for gnome-icon-theme (3.12.0-1ubuntu3) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22+linuxmint1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Setting up ulauncher (4.0.6.r1-0ubuntu1ppa1~xenial) ...
```

Same error on opening pref window

**Comment by Shuunen** [comment] 2018-03-30 14:06
Ok I did rollback the VM to fresh install state to install uLauncher 4, because in the last state I had uLauncher 

Here is what I just did : 

```
chou@choumintou-vm ~ $ cd Téléchargements/

chou@choumintou-vm ~/Téléchargements $ sudo dpkg -i ulauncher_4.0.6.r1_all.deb 
[sudo] Mot de passe de chou : 

Sélection du paquet ulauncher précédemment désélectionné.
(Lecture de la base de données... 204131 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de ulauncher_4.0.6.r1_all.deb ...
Dépaquetage de ulauncher (4.0.6.r1) ...
dpkg: des problèmes de dépendances empêchent la configuration de ulauncher :
 ulauncher dépend de python-levenshtein ; cependant :
  Le paquet python-levenshtein n'est pas installé.
 ulauncher dépend de python-pysqlite2 ; cependant :
  Le paquet python-pysqlite2 n'est pas installé.
 ulauncher dépend de python-websocket ; cependant :
  Le paquet python-websocket n'est pas installé.

dpkg: erreur de traitement du paquet ulauncher (--install) :
 problèmes de dépendances - laissé non configuré
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.15-0ubuntu1) ...
Traitement des actions différées (« triggers ») pour gnome-icon-theme (3.12.0-1ubuntu3) ...
Traitement des actions différées (« triggers ») pour gnome-menus (3.13.3-6ubuntu3.1) ...
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.22+linuxmint1) ...
Traitement des actions différées (« triggers ») pour mime-support (3.59ubuntu1) ...

Des erreurs ont été rencontrées pendant l'exécution :
 ulauncher

chou@choumintou-vm ~/Téléchargements $ sudo apt-get install -f

Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Correction des dépendances... Fait
Les paquets supplémentaires suivants vont être installés :
  python-backports.ssl-match-hostname python-levenshtein python-pysqlite2
  python-websocket
Paquets suggérés :
  python-pysqlite2-doc python-pysqlite2-dbg
Les NOUVEAUX paquets suivants seront installés :
  python-backports.ssl-match-hostname python-levenshtein python-pysqlite2
  python-websocket
0 mis à jour, 4 nouvellement installés, 0 à enlever et 30 non mis à jour.
1 partiellement installés ou enlevés.
Il est nécessaire de prendre 241 ko dans les archives.
Après cette opération, 753 ko d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] 
Réception de:1 http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial/universe amd64 python-levenshtein amd64 0.12.0-2build1 [35,7 kB]
Réception de:2 http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial/universe amd64 python-pysqlite2 amd64 2.7.0-1 [34,1 kB]
Réception de:3 http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial/universe amd64 python-backports.ssl-match-hostname all 3.4.0.2-1 [6 258 B]
Réception de:4 http://bouyguestelecom.ubuntu.lafibre.info/ubuntu xenial/universe amd64 python-websocket all 0.18.0-2 [165 kB]
241 ko réceptionnés en 0s (764 ko/s)  
Sélection du paquet python-levenshtein précédemment désélectionné.
(Lecture de la base de données... 204431 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de .../python-levenshtein_0.12.0-2build1_amd64.deb ...
Dépaquetage de python-levenshtein (0.12.0-2build1) ...
Sélection du paquet python-pysqlite2 précédemment désélectionné.
Préparation du dépaquetage de .../python-pysqlite2_2.7.0-1_amd64.deb ...
Dépaquetage de python-pysqlite2 (2.7.0-1) ...
Sélection du paquet python-backports.ssl-match-hostname précédemment désélectionné.
Préparation du dépaquetage de .../python-backports.ssl-match-hostname_3.4.0.2-1_all.deb ...
Dépaquetage de python-backports.ssl-match-hostname (3.4.0.2-1) ...
Sélection du paquet python-websocket précédemment désélectionné.
Préparation du dépaquetage de .../python-websocket_0.18.0-2_all.deb ...
Dépaquetage de python-websocket (0.18.0-2) ...
Traitement des actions différées (« triggers ») pour doc-base (0.10.7) ...
Traitement de 1 fichier de documentation ajouté…
Enregistrement des documents avec scrollkeeper…
Paramétrage de python-levenshtein (0.12.0-2build1) ...
Paramétrage de python-pysqlite2 (2.7.0-1) ...
Paramétrage de python-backports.ssl-match-hostname (3.4.0.2-1) ...
Paramétrage de python-websocket (0.18.0-2) ...
Paramétrage de ulauncher (4.0.6.r1) ...

chou@choumintou-vm ~/Téléchargements $ ulauncher

/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib

(ulauncher:2641): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

And it's working even with the same errors logged...

**Comment by gornostal** [comment] 2018-03-30 18:09
> what conf/files/folders might still be present and may cause problems to uLaucher 4?

Nothing I can think of. I was trying to reinstall it on your VBox, but Preferences window still won't open.

@Shuunen did you say you were able to reproduce the issue with positioning of the main window as described by @PierfrancescoArdino?
If so, could you tell how?

**Comment by Shuunen** [comment] 2018-03-31 11:51
I did not have issue with window positioning, the issue I got was with Preferences window, then after reboot I also had the black thick corner around uLauncher.

@gornostal If you prefer, I can a new issue

**Comment by gornostal** [comment] 2018-04-01 05:00
@Shuunen please create a new issue for Preferences window if it's still actual for you.
It was resolved by reinstalling Ulauncher v4, wasn't it?

**Comment by Shuunen** [comment] 2018-04-02 00:12
@gornostal no the problem was still there after un-install & re-install, I switched to XFCE desktop now and no problem appearing for now.

**Comment by goodevilgenius** [comment] 2019-02-18 16:51
I have the positioning issue, although not the focus issue, on Fluxbox under X11.

**Comment by gornostal** [comment] 2019-02-20 05:59
@goodevilgenius do you mind creating a new issue for that please?
This one is about window position in Wayland, which requires a different solution, I think.

Thanks

**Comment by gexter-sangsongthong** [comment] 2021-11-22 13:49
I don't know if the bug has been fixed or not but I worked around by setting "center new window" to "on" using Gnome Tweak Tool and it works. It moves from top left corner to top center which was less annoying. It works on Manjaro Gnome running on Wayland.

**Comment by danieltomasz** [comment] 2021-11-24 11:55
Thanks for the workaround! On Ubuntu 21.10 it solved my problems!

**Comment by friday** [comment] 2022-03-18 23:26
I'm going to close this. Ulauncher officially only supports running in XWayland, with `GDK_BACKEND=x11`. As of Ulauncher v6 (upcoming) this will be the default for all ways to start the ulauncher service, while in Ulauncher v5 you need to set `GDK_BACKEND=x11` when starting ulauncher via the command.

"center new window" is not a sufficient solution as the Ulauncher height is dynamic and we have to have control of how to position it ourselves or it will lead to annoying behavior. Additionally this affects other windows than Ulauncher, and we need XWayland anyway for other functionality, like the ability to move the window (new in upcoming Ulauncher v6 release).

More info in #991

**Closed by friday** 2022-03-18 23:26 UTC
Labels: bug, no solution :man_shrugging:

**Comment by hedgieinsocks** [comment] 2024-06-28 06:25
Since xwayland caused black box flashing for me (https://github.com/Ulauncher/Ulauncher/issues/1399), I've tackled the issue by editing CSS for the custom theme I use. This way I can now force the ulauncher window to appear wherever I please on wayland.

1) in ulauncher prefs set the window width to max of your display (in my case 1920)
2) edit `margin` values under `.app` (in my case `160px 640px 180px 640px;`) 

I'm using ulauncher-theme-libadwaita theme so that's the line to edit https://github.com/leodr/ulauncher-theme-libadwaita/blob/59ba686189726ba0cbb59c0a60287e48378f7eec/theme.css#L40
