### ISSUE TITLE
 urlopen error SSL certificate verify failed 

### ISSUE THREAD

**Issue by aamehedi** [Ulauncher/Ulauncher#543] opened 2020-04-14 10:08 UTC
### Steps to reproduce
1. Open Ulauncher
2. Open Ulauncher Settings->Extensions->Add Extension
3. Add any extension

### Current behavior
It's not install the extension.

### Expected behavior
It should install the extension.

### Environment
**Ulauncher version**: v5.7.3
**Linux distro**: LInux Mint 19.3
**Desktop environment**: Cinnamon 4.4.8

### Logs
[Link to Gist](https://gist.github.com/aamehedi/654bedd0a202a59ec5ab23e1a7611c56)

### Note
- I can `curl -v https://github.com`
- I have ran `sudo update-ca-certificates`
- I have no firewall enabled
- I can browse to that extension and download zip

**Comment by friday** [comment] 2021-09-05 09:10
Duplicate of #424

**Closed by friday** 2021-09-05 09:10 UTC
