### ISSUE TITLE
VERY HIGH RAM USAGE

### ISSUE THREAD

**Issue by VladimirMikulic** [Ulauncher/Ulauncher#590] opened 2020-07-13 16:37 UTC
Hi!

Vanilla ULauncher is great & extremely fast but its extensions are not so great at memory usage.
On my Kubuntu 20.04 each ULauncher extension consumes ~50Mb -> 4 extensions = 200Mb of RAM!
I was thinking of adding more of them, but when I saw 50Mb per extension, I got a mini heart attack :)

![ulauncher](https://user-images.githubusercontent.com/35997844/87329498-53525800-c537-11ea-9923-e3c9f9971854.png)

Are there any optimization plans/features coming to address this issue?

Thanks.

**Comment by friday** [comment] 2020-08-15 14:56
There's an old issue about this #285

**Comment by VladimirMikulic** [comment] 2020-08-15 18:57
Thanks, @friday, but nothing has changed :(

**Comment by friday** [comment] 2021-08-20 17:22
Closing as a duplicate of #285

**Closed by friday** 2021-08-20 17:22 UTC
