### ISSUE TITLE
Preferences not working

### ISSUE THREAD

**Issue by jooops** [Ulauncher/Ulauncher#268] opened 2018-08-15 14:48 UTC
![selection_280](https://user-images.githubusercontent.com/8640365/44154158-60aadcb0-a0aa-11e8-9e28-046b2077e209.jpg)

**Steps to reproduce:**
When I try to click on Preferences the application show a white window with "Loading ..." and then when I try to click in other parts the window disappear and remain like in the picture

**Ulauncher version**: 4.1.0.r1
**Linux distro**: debian with kernel 4.17.0-2-amd64
**Desktop environment**: mate 1.20.3

**Logs**:

https://gist.github.com/jooops/5cd0bcaacd81400e0af988283fe098cd

**Comment by gornostal** [comment] 2018-08-19 07:13
Looks like there are some incompatibility issues when using the latest versions of GTK and other packages.

It would be great if you could provide a virtual box image with the environment where the bug can be reproduced.

**Comment by Apuyuseng** [comment] 2019-04-12 07:20
Can you tell me how to solve the problem?

**Comment by napkinator** [comment] 2019-09-26 07:58
![2019-09-26_09-57](https://user-images.githubusercontent.com/55829009/65669557-123e9500-e044-11e9-8d7f-61275257fb89.png)

Same problem here with Fedora 30.

**Comment by gornostal** [comment] 2020-01-07 20:16
@napkinator if this is still actual for you, could you attach the full logs please? They are in `~/.local/share/ulauncher/last.log`

I'm not sure if it will help me to boil down the problem, but at least I can compare GTK version with what I have.

Also, ulauncher depends on package called `webkitgtk4`. Could you find out what version of that package you have? I think that should help.

Thanks

**Comment by napkinator** [comment] 2020-01-08 10:15
Here are the content of `~/.local/share/ulauncher/last.log`

[ulauncher_lastlog.txt](https://github.com/Ulauncher/Ulauncher/files/4034717/ulauncher_lastlog.txt)

Related to `webkitgtk4`, i don't have installed a package with this name:

`dnf list installed | grep -i webkitgtk4`

Maybe this is the problem?

**Comment by gornostal** [comment] 2020-01-08 11:43
That could be a problem. Could you try to install it?

**Comment by napkinator** [comment] 2020-01-08 12:13
I saw, that the package `webkitgtk4` was renamed to `webkit2gtk3`.

```
dnf list installed | grep -i webkit2gtk3
webkit2gtk3.x86_64                                2.26.2-1.fc30
```

**Comment by gornostal** [comment] 2020-01-08 16:10
maybe it was renamed, but it should still work with webkit2gtk3

I've found Fedora 30, installed ulauncher and it works

**Comment by napkinator** [comment] 2020-01-09 07:53
I've tested it on Fedora 31 and get the same error here. webkit2gtk3 is installed in the same version.

```
dnf list installed | grep -i webkit2gtk3
webkit2gtk3.x86_64                                 2.26.2-1.fc31
```

Anything else i can debug?

**Comment by gornostal** [comment] 2020-01-09 17:45
@napkinator you can try shutting down ulauncher and then running it with `ulauncher -v`

Then observe any errors or warnings in the console when it's started and when you open Preferences.
Some logs that come from GTK are not written to `last.log` file, so you may be able to see the error that can explain this behavior

**Comment by napkinator** [comment] 2020-01-10 08:06
Here are the logs.

[ulauncher-v_lastlog.txt](https://github.com/Ulauncher/Ulauncher/files/4044517/ulauncher-v_lastlog.txt)

 At line 183 there is a "Gdk-CRITICAL"-Message. Could this be related to that issue?

**Comment by gornostal** [comment] 2020-01-11 11:42
No that critical error is not critical. I saw it in my Manjaro VBox today and ulauncher was working fine.
It's something else...

**Comment by chrisaltdel** [comment] 2020-07-01 06:49
In the meanwhile i'm on Fedora32 and this issue still exist.

**Comment by friday** [comment] 2021-10-04 20:48
I'm closing as a duplicate of #114. Not fully sure it is the same cause, but at least the same symptom.

**Closed by friday** 2021-10-04 20:48 UTC
Labels: bug, severity-medium
