### ISSUE TITLE
unexpected API error. KeyError when saving plugins

### ISSUE THREAD

**Issue by ghost** [Ulauncher/Ulauncher#354] opened 2019-03-12 21:28 UTC
### Steps to reproduce
1. install plugin
2. press save
3. get an error

### Current behavior
getting an error 
```
unexpected API error. KeyError: 
com.github.martindiphoorn.ulauncher-2fa
```

### Expected behavior
plugin settings save

### Environment
**Ulauncher version**: v4.3.2.r8
**Linux distro**: fedora
**Desktop environment**: xfce

same issue with plugins:
https://ext.ulauncher.io/-/github-brpaz-ulauncher-currency
https://ext.ulauncher.io/-/github-martindiphoorn-ulauncher-2fa
https://ext.ulauncher.io/-/github-iyim-keepassplugin-ulauncher

**Comment by friday** [comment] 2019-03-12 21:31
That looks truncated. Could you paste the whole error with the stack and line number?

**Comment by rumjantsevv** [comment] 2019-03-12 21:34
@friday that's the hole error i'm getting in modal window

**Comment by friday** [comment] 2019-03-12 21:38
I see. Could you follow these instructions to get the full error log:
  * Close ulauncher
  * Run "ulauncher -v" from the console
  * Copy and past the relevant parts or the whole log output here.

**Comment by rumjantsevv** [comment] 2019-03-12 21:42
@friday tried to do that before creating an issue, but it also dosn't work(just printing some warning to console and closes)

warning:
```
/usr/lib/python2.7/site-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib

```

**Comment by friday** [comment] 2019-03-12 22:41
Alright. I guess then the error in the modal window "swallows" the error in the console, without printing the verbose info.

Thanks for following my instructions :+1: and sorry they weren't helpful in this case! Since we know the error type and that the key is an extension id, at least that's a place to start. It happens because Ulauncher is trying to access an extension which hasn't yet been loaded yet. I think it's likely due to some other problem while trying to load it. Looking at the [source](https://github.com/Ulauncher/Ulauncher/blob/f18e1a748144f9b625b1ae182039465b1990ecee/ulauncher/api/server/ExtensionRunner.py#L112), these seems to be mostly handled (apart from this specific line which doesn't seem likely to happen here), so I don't think I can help you without a stack track or being able to reproduce it myself. @gornostal possibly can (though he has a lot else on his table).

In case you haven't: I would try removing extensions, restarting Ulauncher and reinstalling them (not necessarily in that order). It might not work.

**Comment by rumjantsevv** [comment] 2019-03-13 05:34
> In case you haven't: I would try removing extensions, restarting Ulauncher and reinstalling them (not necessarily in that order). It might not work.

Tried :(

**Comment by brpaz** [comment] 2019-03-16 12:35
From my experience, this error, usually means the extension has a missing python dependency. I had many issues opened in my extensions because of that. Thats why I think #273 should be high priority.

**Comment by rumjantsevv** [comment] 2019-03-22 20:30
>Do this and look for errors on the output, but not when your are changing the extension settings, but on the ulauncher startup
i tried this at the ulauncher startup, not while saving extension settings

**Comment by friday** [comment] 2021-08-12 12:22
Closing this. It's two separate issues. Ine is covered in #767 and the other in #772

**Closed by friday** 2021-08-12 12:22 UTC
Labels: bug, severity-high
