### ISSUE TITLE
About section still shows 2.0.14 as the version number

### ISSUE THREAD

**Issue by GGimenez96** [Ulauncher/Ulauncher#102] opened 2017-03-08 16:50 UTC

**Comment by gornostal** [comment] 2017-03-08 16:52
Can you provide more details?
Your OS, where you downloaded the app.

**Comment by GGimenez96** [comment] 2017-03-08 16:53
Ubuntu 16.04.2 LTS. I downloaded it from the Download section of the official site (http://ulauncher.io/).

**Comment by gornostal** [comment] 2017-03-08 16:54
Thanks for reporting this issue.
I'll look into it

**Comment by gornostal** [comment] 2017-03-09 13:33
@GGimenez96 I cannot reproduce this issue.
Try to install this deb package again
https://github.com/Ulauncher/Ulauncher/releases/download/2.0.30.r3/ulauncher_2.0.30.r3_all.deb

**Comment by GGimenez96** [comment] 2017-03-10 15:21
I don't know why it happened. I noticed that after restarting my PC it was fixed.

**Comment by gornostal** [comment] 2017-03-10 15:25
OK. Closing this ticket.

**Closed by gornostal** 2017-03-10 15:25 UTC
Labels: bug, waiting-response
