### ISSUE TITLE
Can't bind to "Super" key only? (there's a workaround in comments)

### ISSUE THREAD

**Issue by mdhenriksen** [Ulauncher/Ulauncher#341] opened 2019-01-30 16:22 UTC
Hi! 

Awesome launcher and features. Really love it!

However, it seems I can't bind the **Super** key to launch it? I can bind "Super + 'something'" but not Super-only. Is there anyway this can be achieved?

**Using Ubuntu 18.10 by the way**

**Comment by friday** [comment] 2019-01-30 16:59
Super is a modifier. It doesn't trigger a normal key press event. If you want it to act like a plain key when you press and release immediately without hitting any other keys this is called "dual-role" keys. You have to use something like `xcape` (X11 only) for that. There's no good alternative for wayland.

**Comment by aasmpro** [comment] 2019-02-10 23:41
using `debian buster` with `xfce4` DE, installed latest version of ulauncher `v4.3.1.r4` and set Hotkey to `Super L`, it works great.

**Comment by gornostal** [comment] 2019-02-23 18:02
@aasmpro thanks for providing a workaround.

> Can't bind to "Super" key only
That's s by design as explained by @friday.

I'm closing this issue.

**Closed by gornostal** 2019-02-23 18:02 UTC

**Comment by friday** [comment] 2019-02-25 23:50
I just learned you can do this in Gnome too if you unset Mutter's `overlay-key` and then bind to `Super_L`. You have to use dconf or gsettings since the GUI keyboard settings is restricted by the same reason as already mentioned.

This should work:

```
CKBPATH=org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
# Disable default mapping for Super 
gsettings set org.gnome.mutter overlay-key ''
# Add custom keybinding for Ulauncher
gsettings set $CKBPATH/ulauncher/ name 'ulauncher'
gsettings set $CKBPATH/ulauncher/ command 'ulauncher-toggle'
gsettings set $CKBPATH/ulauncher/ binding 'Super_L'
```

While it doesn't break Super L as a modifier key it will show ulauncher when you press Super, not like Mutter's `overlay-key`, which is implemented as a real dual-role key. I suspect some or hard coded logic is to blame for the inconsistency. `xcape` is still my recommendation.

Restoring the defaults:

```
CKBPATH=org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
gsettings reset org.gnome.mutter overlay-key
gsettings reset-recursively $CKBPATH/ulauncher/

```

**Comment by Vondelphia** [comment] 2021-03-27 19:51
Hey @friday - might you know how to use xcape to get this to work, specifically? I was [browsing over the github](https://github.com/alols/xcape) but the usage part is like gibberish. Maybe I have to slow down :smirk: :joy: 

I run / install in terminal: `sudo dnf copr enable dawid/xcape` ... and than install xcape and run `xcape -e 'Super_L=F1'` but when I press SUPER key it doesn't fire off an F1 (which is what I have bound to launch Ulauncher).

Thanks in advance and hope all is well.
