### ISSUE TITLE
Prioritize exact matches?

### ISSUE THREAD

**Issue by ckp95** [Ulauncher/Ulauncher#700] opened 2021-02-28 23:16 UTC
I'm not sure if this is a bug but it's a bit annoying. When I type things, exact matches aren't prioritized. For example, when typing "thunar`, the Thunar program is not the top match (this is on a fresh install):

![image](https://user-images.githubusercontent.com/43073868/109437023-acb1bd80-7a1a-11eb-878e-c81dfa0effee.png)

I couldn't find a setting to prioritize exact matches.

In practice this isn't a huge problem because Ulauncher remembers frequently chosen options, so Thunar appears at the top after having chosen it before. But it's still a bit annoying for rarely used programs.

**Comment by KuenzelIT** [comment] 2021-04-29 11:24
Probably a duplicate of #232

**Comment by friday** [comment] 2021-08-20 16:50
This is fixed in 5.12.0, that was just released for Arch and Ubuntu/Debian packages. The Fedora build will be released soon too.

**Closed** 2021-08-20 16:50 UTC
