### ISSUE TITLE
ULauncher not working after latest upgrade

### ISSUE THREAD

**Issue by antonio-petricca** [Ulauncher/Ulauncher#842] opened 2021-11-07 15:25 UTC
Hi, I just applied latest ULuancher upgrade, it does not start any applications.

Here a log of the error:

> 2021-11-07 16:24:31,502 | INFO | ulauncher.api.shared.action.LaunchAppAction: run() | Run application Text Editor (/usr/share/applications/xed.desktop) Exec xed %U
Job for run-r5d4df67bf6a24568a6960ad89d9b1105.scope failed.
See "systemctl status run-r5d4df67bf6a24568a6960ad89d9b1105.scope" and "journalctl -xe" for det

**Comment by troycurtisjr** [comment] 2021-11-07 19:11
Can you follow the issue template so that we have all the necessary information to try to help you troubleshoot?

**Comment by antonio-petricca** [comment] 2021-11-07 20:15
Sorry, here are all the details:

### Steps to reproduce

1. Upgrade to latest release.
2. try to start any application

### Current behavior

It starts no more applications.

### Expected behavior

It must run the selection application.

### Environment
**Ulauncher version**: 5.14.0-0ubuntu1ppa1~bionic 
**Linux distro**: Linux Mint 19.3 (Ubuntu 18.04)
**Desktop environment**: MATE

### Logs

> 2021-11-07 16:24:31,502 | INFO | ulauncher.api.shared.action.LaunchAppAction: run() | Run application Text Editor (/usr/share/applications/xed.desktop) Exec xed %U
Job for run-r5d4df67bf6a24568a6960ad89d9b1105.scope failed.
See "systemctl status run-r5d4df67bf6a24568a6960ad89d9b1105.scope" and "journalctl -xe" for det

**Comment by antonio-petricca** [comment] 2021-11-07 22:13
Some other logs:

> 2021-11-07 23:11:58,261 | INFO | ulauncher.api.shared.action.LaunchAppAction: run() | Run application Vivaldi (/usr/share/applications/vivaldi-stable.desktop) Exec /usr/bin/vivaldi-stable %U
Job for run-r98cfa415db314d6787bd1602aa523a70.scope failed.

**Comment by troycurtisjr** [comment] 2021-11-07 22:46
We saw something similar with someone running an alternate arch Kali distro (running on Android). Are you running on standard x86 hardware? I will try to reproduce in a VM.

**Comment by antonio-petricca** [comment] 2021-11-08 06:31
I runs ULauncher since 2 or 3 years on Delle E5495 equipped with an Amd Ryzen 7 PRO, 16Gb RAM, 512Gb SSD.

As I stated previously it ran until yesterday, before I downloaded the latest release from the official PPA.

If I create a new linux user it works as expected, so I suspect that the upgrade processes changed something into the old user profile settings. 

Maybe?

**Comment by sk011** [comment] 2021-11-08 07:51
same problem 
Ubuntu 18.04.6 LTS 
Desktop XFCE
Version 5.14.0-0ubuntu1ppa1~bionic

at startup any app
```
wpc systemd[3287]: run-r9fb87dcedb5e493497f9a7e1b31164e6.scope: Failed to add PIDs to scope's control group: Permission denied
wpc systemd[3287]: run-r9fb87dcedb5e493497f9a7e1b31164e6.scope: Failed with result 'resources'.
wpc systemd[3287]: Failed to start /usr/bin/doublecmd.

```

**Comment by antonio-petricca** [comment] 2021-11-08 07:52
Downgrading to the previous release does not solve the issue.

**Comment by antonio-petricca** [comment] 2021-11-08 13:40
Unfortunately I had to switch to https://albertlauncher.github.io which works with no problems. :(

**Comment by Jaakkonen** [comment] 2021-11-09 08:39
I've got same problem with `systemd 249 (249.r1901.g5c12ee3656-1-arch)` and ulauncher release version `5.14.0` and latest dev commit `5.14.0.r3.g25c9a33-1`.
```
Nov 09 10:21:27 hostname systemd[762]: Created slice Slice /app/code.
Nov 09 10:21:27 hostname systemd[762]: Created slice Slice /app/code/oss.
Nov 09 10:21:27 hostname systemd[762]: run-r6ee1e753af7c4dff859ccf5d721f619a.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 09 10:21:27 hostname systemd[762]: run-r6ee1e753af7c4dff859ccf5d721f619a.scope: Failed with result 'resources'.
Nov 09 10:21:27 hostname systemd[762]: Failed to start /usr/bin/code-oss --unity-launch.
Nov 09 10:21:27 hostname sway[81270]: Job failed. See "journalctl -xe" for details.
```
It looks like I'm encountering the same issue with just `systemd-run`:
```sh
$ systemd-run --user --scope code-oss
Job failed. See "journalctl -xe" for details.
$ journalctl -eb --user
Nov 09 10:33:46 hostname systemd[762]: run-r036b97487337439cbaf83f05a0a857df.scope: No PIDs left to attach to the scope's control group, refusing: Success
Nov 09 10:33:46 hostname systemd[762]: run-r036b97487337439cbaf83f05a0a857df.scope: Failed with result 'resources'.
Nov 09 10:33:46 hostname systemd[762]: Failed to start /usr/bin/code-oss.
```
However `systemd-run --user -r code-oss` seems to be working fine. It runs programs in services instead of scopes and those remain in `systemctl --user` output as exited after those have been closed. `-r` is required for forking programs as otherwise systemd will just kill the service and its children when the forking process exists.

So it looks like just a couple line hotfix to https://github.com/Ulauncher/Ulauncher/blob/dev/ulauncher/api/shared/action/LaunchAppAction.py#L60 should work.

**Comment by rrondeau** [comment] 2021-11-09 13:18
Same problem here with :
Fedora 35
ulauncher 5.14.0
systemd 249

**Comment by troycurtisjr** [comment] 2021-11-09 14:17
So strange since that is my current setup as well and it seems to work. Though I am starting as a user systemd service.  Are you using systemd or the "autostart" configuration in the preferences dialog? (BTW in V6 we'll only be using systemd to autostart so this difference will no longer exist)

**Comment by rrondeau** [comment] 2021-11-09 14:23
I'm using the "Launch at login" checkbox in the preferences.

**Comment by rrondeau** [comment] 2021-11-09 14:30
I just switched to systemd user service, this solved the issue for my setup, thanks !

**Comment by friday** [comment] 2021-11-09 17:16
Based on the error posted by Jaakkonen I think the reason we're seeing so many of these reports now is because we for a period of time didn't have a Bionic build on Launchpad (until #839), and it seems this is due to https://github.com/systemd/systemd/issues/3388, which was a regression, so it actually worked in Xenial, but not Bionic, and it was fixed over 3 years ago, so later Ubuntu releases shouldn't have this issue https://github.com/systemd/systemd/pull/8125

I don't know why it's happening on Fedora and Arch though. There's details in the issue how to work around it, but we need to fix this in Ulauncher instead.

I think switching to the `-r` option (aka `--remain-after-exit`) and making a new patch release asap is a good idea. When investigating this initially I found some reason not to, but I can't recall why now.

**Comment by friday** [comment] 2021-11-09 17:18
> I'm using the "Launch at login" checkbox in the preferences.

We are switching that to use systemd directly, so eventually those will be the same. The work has already been done, but it will be pushed as part of a major/breaking release with a lot of other things.

**Comment by friday** [comment] 2021-11-09 18:12
Didn't mean to close this until released/confirmed

**Comment by friday** [comment] 2021-11-09 18:19
I pushed a pre-release for 5.14.1: https://github.com/Ulauncher/Ulauncher/releases/tag/5.14.1-beta1

It would be great if someone on Ubuntu Bionic in particular could test this before we push the regular release.

**Comment by Jaakkonen** [comment] 2021-11-10 09:12
The fix seems to have worked at least on my Arch setup :)

**Comment by sk011** [comment] 2021-11-10 09:30
> I pushed a pre-release for 5.14.1: https://github.com/Ulauncher/Ulauncher/releases/tag/5.14.1-beta1
> 
> It would be great if someone on Ubuntu Bionic in particular could test this before we push the regular release.

Ubuntu 18.04.6 LTS bionic
looks good, no error in journal

`wpc systemd[3150]: Started /usr/bin/mate-calc.`

**Comment by friday** [comment] 2021-11-10 15:07
Thank you @Jaakkonen and @sk011

I pushed the pre-release as 5.14.1, so it the official release now :)
https://github.com/Ulauncher/Ulauncher/releases/tag/5.14.1

Fedora will get it a bit later, but I'll close the issue.

**Comment by boris-petrov** [comment] 2021-11-12 08:52
I have the same issue on ArchLinux with version 5.14.1. Upgraded yesterday, I guess I was on the version before 5.14.0 (of course I cleaned my cached packages so I'm not exactly sure). Any suggestions?

**Comment by friday** [comment] 2021-11-12 22:20
We're still looking at this since 5.14.1 introduced more issues than it fixed it seems (although the issues it fixed may have been more critical)

**Comment by friday** [comment] 2021-11-12 22:21
> I have the same issue on ArchLinux with version 5.14.1. Upgraded yesterday, I guess I was on the version before 5.14.0 (of course I cleaned my cached packages so I'm not exactly sure). Any suggestions?
> 
> P.S. So I've upgraded from 5.14.0. I just downgraded to it and it works fine. So I'm having issues only with 5.14.1.

What's your error log output? Are you running Ulauncher as a systemd service?

**Comment by antonio-petricca** [comment] 2021-11-13 10:00
The latest update fixed the issue for me. Thank you.

**Comment by timothyjlaurent** [comment] 2021-11-13 20:59
I'm running v5.14.1 and still can't launch anything.

**Comment by scrool** [comment] 2021-11-14 10:27
**Fedora 35**: before this fix when I started ulauncher after start (with a checkbox in the application) it didn't start any application.

After installation of an update in testing https://bodhi.fedoraproject.org/updates/FEDORA-2021-aae7b9d3dc ulauncher is able to launch applications again. :+1: 

Thanks!

**Comment by friday** [comment] 2021-11-14 22:04
Cross-posted from #854:

[5.14.2](https://github.com/Ulauncher/Ulauncher/releases/tag/5.14.2) released. This release should fix the issue for most users and all users not using systemd to start Ulauncher (you would know if you use systemd for this).

Up until this point we have been moving towards switching the recommended way to run Ulauncher to systemd, because it's a more configurable and powerful way, than handles and restarts Ulauncher if it should crash and similar. This introduced a problem for us that meant we had to use `systemd-run` to launch apps, and this in turn introduced the issue with apps not launching at all for users with old systemd versions, and apparently some with newer versions were affected too (not fully sure why).

If you **had the issue on 5.14.0** and you **use systemd to run Ulauncher**, then you will still be affected by the issue. This is probably the best we can do, since we can't fix users systemd setups. You can try to fix it yourself looking at the systemd issue https://github.com/systemd/systemd/issues/3388, or just switch from systemd to using using Ulauncher's preferences to enable autostart (this option doesn't use systemd).

We will reevaluate our stance on recommending systemd and update our documentation where needed.

**Closed by friday** 2021-11-14 22:04 UTC
