### ISSUE TITLE
Sorting issue - existing command should be the first one (fuzzy search improvements)

### ISSUE THREAD

**Issue by sukovec** [Ulauncher/Ulauncher#336] opened 2019-01-20 16:45 UTC
Hello. I installed ulauncher yesterday (came from gmrun). So far so good. But today I wanted to run gimp, so I inserted "gimp" into line and pressed enter... and gvim has been launched. [Can be seen on image](https://sh.sukovec.cz/upload/gimp-gvim.png)

**Steps to reproduce:**
- Install gvim & gimp
- Insert "gimp" into ulauncher

**Ulauncher version**: 4.3.1.r4
**Linux distro**: Arch, 4.20.1-zen1-1-zen x86_64
**Desktop environment**: i3wm

**Comment by sukovec** [comment] 2019-01-21 20:05
Okay, it looks like I mis-interpreted purpose of this software - I was looking on it as "cool and good looking command launcher" but it's probably more like program launcher?

**Comment by gornostal** [comment] 2019-01-22 18:03
> it's probably more like program launcher

Yes, that's right.

**Comment by gornostal** [comment] 2019-01-22 18:03
The issue is related to #232. 
Will be fixed along with it.

**Comment by sukovec** [comment] 2019-01-22 18:16
One time, it happened to me that I wrote something too fast after launch and expected program was not in the list (re-writing it after a while reveals that finally). Is it also related with #232 or should I raise new bug? I cannot see anything more related...


> > it's probably more like program launcher
> Yes, that's right.
So, I cannot expect some support to just exec plain commands? Sometimes I just need to run simple command (like `i3 restart`, `reboot` or `shutdown`) - for which is small launcher window more suitable (as I don't need to create new terminal windows in tiling layout).

**Comment by gornostal** [comment] 2019-01-22 18:25
> ... wrote something too fast after launch and expected program was not in the list (re-writing it after a while reveals that finally)

That can happen when you start Ulauncher for the first time and start typing a query while it's indexing apps in the background. It's not a bug if that's your case.

> Sometimes I just need to run simple command (like i3 restart, reboot or shutdown) 

You can do that with Ulauncher. There are several ways.
First, you can check out if there's an extension for that here https://ext.ulauncher.io/.
I saw several extensions that provide commands for shutdown, reboot, log out.
If that doesn't suit you, you can open Preferences, go to Shortcuts and create a shortcut that will run a shell command. You will still have to use some prefix like `cmd i3 restart`, because by default Ulauncher query is used to search apps

**Comment by friday** [comment] 2019-01-23 23:04
This may also be of interest @sukovec: https://github.com/Ulauncher/Ulauncher/issues/191#issuecomment-457000841

**Comment by friday** [comment] 2021-12-03 16:14
I consider this to be fixed in the Ulauncher v6 branch (with this PR: #827). It won't be released for a while, but we made a tracking issue if you want to be notified #869

There are still some things that make this less straight forward:
The natural sorting of the apps should solve this now, but there are two additional features that come into play as well.
1. Apps are searchable by their binary names (for example most of the Gnome suit apps have more unique binary names. "Files" is named "nautilus", and some know these apps by these names or find them better for searching)
2. If you enter for example "gi" and launch gvim, Ulauncher will remember this and put gvim on top the next time for the "gi" query.

Regarding plain commands you could run commands via an extension. There are several that does that: https://ext.ulauncher.io/

**Closed by friday** 2021-12-03 16:14 UTC
Labels: enhancement
